[package]
name = "rmesh_python"
version = "0.1.0"
edition = "2024"

[lib]
name = "rmesh"
crate-type = ["cdylib"]

[dependencies]
anyhow = {workspace=true}
bytemuck = {workspace=true}
nalgebra = {workspace=true}
once_cell = {workspace=true}
rmesh = { path = "../rmesh", features = ["wgpu"] }
rmesh_viewer = { path = "../rmesh_viewer" }
image = "0.25"
serde_json = "1.0"

numpy = "0.27"
pyo3 = { version = "0.27", features=["anyhow", "abi3-py310"] }

[dev-dependencies]
approx = "0.5.1"
nalgebra = { version = "0.33.2", features=["bytemuck"] }
