//! Auto-generated AP214 entity definitions.
//!
//! ## Adding a new entity type
//!
//! 1. Add the entity's EXPRESS name (lowercase) to `TYPED_ENTITIES` in
//!    `crates/codegen/src/generator.rs`.
//! 2. Run: `cargo run -p codegen -- ./reference/APs/10303-214e3-aim-long.exp \
//!         -o crates/rmesh/src/boundary/step/ap214.rs`
//! 3. Use in mod.rs: `ap214::Entity::NewEntity(e) => { ... }`

// Autogenerated file, do not hand-edit!
#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::all)]
#![allow(clippy::pedantic)]
#![allow(clippy::restriction)]
#![allow(clippy::nursery)]

use super::parse::{Derived, IResult, Logical, Parse, param_from_chunks, parse_complex_mapping};
use arrayvec::ArrayVec;
use nom::{
    bytes::complete::tag,
    character::complete::{alpha0, alphanumeric1},
    combinator::recognize,
    multi::many0,
    sequence::pair,
};

#[derive(Debug)]
pub struct CartesianPoint_<'a> {
    pub name: &'a str,
    pub coordinates: ArrayVec<f64, 3>,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> CartesianPoint_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("CARTESIAN_POINT(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, coordinates) = param_from_chunks::<ArrayVec<f64, 3>>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                coordinates,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct Direction_<'a> {
    pub name: &'a str,
    pub direction_ratios: ArrayVec<f64, 3>,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> Direction_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("DIRECTION(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, direction_ratios) = param_from_chunks::<ArrayVec<f64, 3>>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                direction_ratios,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct Vector_<'a> {
    pub name: &'a str,
    pub orientation: usize,
    pub magnitude: f64,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> Vector_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("VECTOR(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, orientation) = param_from_chunks::<usize>(false, s, &mut i, strs)?;
        let (s, magnitude) = param_from_chunks::<f64>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                orientation,
                magnitude,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct Axis2Placement3d_<'a> {
    pub name: &'a str,
    pub location: usize,
    pub axis: Option<usize>,
    pub ref_direction: Option<usize>,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> Axis2Placement3d_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("AXIS2_PLACEMENT_3D(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, location) = param_from_chunks::<usize>(false, s, &mut i, strs)?;
        let (s, axis) = param_from_chunks::<Option<usize>>(false, s, &mut i, strs)?;
        let (s, ref_direction) = param_from_chunks::<Option<usize>>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                location,
                axis,
                ref_direction,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct Line_<'a> {
    pub name: &'a str,
    pub pnt: usize,
    pub dir: usize,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> Line_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("LINE(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, pnt) = param_from_chunks::<usize>(false, s, &mut i, strs)?;
        let (s, dir) = param_from_chunks::<usize>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                pnt,
                dir,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct Circle_<'a> {
    pub name: &'a str,
    pub position: usize,
    pub radius: f64,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> Circle_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("CIRCLE(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, position) = param_from_chunks::<usize>(false, s, &mut i, strs)?;
        let (s, radius) = param_from_chunks::<f64>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                position,
                radius,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct Ellipse_<'a> {
    pub name: &'a str,
    pub position: usize,
    pub semi_axis_1: f64,
    pub semi_axis_2: f64,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> Ellipse_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("ELLIPSE(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, position) = param_from_chunks::<usize>(false, s, &mut i, strs)?;
        let (s, semi_axis_1) = param_from_chunks::<f64>(false, s, &mut i, strs)?;
        let (s, semi_axis_2) = param_from_chunks::<f64>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                position,
                semi_axis_1,
                semi_axis_2,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct BSplineCurve_<'a> {
    pub name: &'a str,
    pub degree: i64,
    pub control_points_list: Vec<usize>,
    pub curve_form: &'a str,
    pub closed_curve: Logical,
    pub self_intersect: Logical,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> BSplineCurve_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("B_SPLINE_CURVE(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, degree) = param_from_chunks::<i64>(false, s, &mut i, strs)?;
        let (s, control_points_list) = param_from_chunks::<Vec<usize>>(false, s, &mut i, strs)?;
        let (s, curve_form) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, closed_curve) = param_from_chunks::<Logical>(false, s, &mut i, strs)?;
        let (s, self_intersect) = param_from_chunks::<Logical>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                degree,
                control_points_list,
                curve_form,
                closed_curve,
                self_intersect,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct BSplineCurveWithKnots_<'a> {
    pub name: &'a str,
    pub degree: i64,
    pub control_points_list: Vec<usize>,
    pub curve_form: &'a str,
    pub closed_curve: Logical,
    pub self_intersect: Logical,
    pub knot_multiplicities: Vec<i64>,
    pub knots: Vec<f64>,
    pub knot_spec: &'a str,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> BSplineCurveWithKnots_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("B_SPLINE_CURVE_WITH_KNOTS(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, degree) = param_from_chunks::<i64>(false, s, &mut i, strs)?;
        let (s, control_points_list) = param_from_chunks::<Vec<usize>>(false, s, &mut i, strs)?;
        let (s, curve_form) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, closed_curve) = param_from_chunks::<Logical>(false, s, &mut i, strs)?;
        let (s, self_intersect) = param_from_chunks::<Logical>(false, s, &mut i, strs)?;
        let (s, knot_multiplicities) = param_from_chunks::<Vec<i64>>(false, s, &mut i, strs)?;
        let (s, knots) = param_from_chunks::<Vec<f64>>(false, s, &mut i, strs)?;
        let (s, knot_spec) = param_from_chunks::<&'a str>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                degree,
                control_points_list,
                curve_form,
                closed_curve,
                self_intersect,
                knot_multiplicities,
                knots,
                knot_spec,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct RationalBSplineCurve_<'a> {
    pub name: &'a str,
    pub degree: i64,
    pub control_points_list: Vec<usize>,
    pub curve_form: &'a str,
    pub closed_curve: Logical,
    pub self_intersect: Logical,
    pub weights_data: Vec<f64>,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> RationalBSplineCurve_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("RATIONAL_B_SPLINE_CURVE(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, degree) = param_from_chunks::<i64>(false, s, &mut i, strs)?;
        let (s, control_points_list) = param_from_chunks::<Vec<usize>>(false, s, &mut i, strs)?;
        let (s, curve_form) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, closed_curve) = param_from_chunks::<Logical>(false, s, &mut i, strs)?;
        let (s, self_intersect) = param_from_chunks::<Logical>(false, s, &mut i, strs)?;
        let (s, weights_data) = param_from_chunks::<Vec<f64>>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                degree,
                control_points_list,
                curve_form,
                closed_curve,
                self_intersect,
                weights_data,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct Plane_<'a> {
    pub name: &'a str,
    pub position: usize,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> Plane_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("PLANE(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, position) = param_from_chunks::<usize>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                position,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct CylindricalSurface_<'a> {
    pub name: &'a str,
    pub position: usize,
    pub radius: f64,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> CylindricalSurface_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("CYLINDRICAL_SURFACE(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, position) = param_from_chunks::<usize>(false, s, &mut i, strs)?;
        let (s, radius) = param_from_chunks::<f64>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                position,
                radius,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct ConicalSurface_<'a> {
    pub name: &'a str,
    pub position: usize,
    pub radius: f64,
    pub semi_angle: f64,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> ConicalSurface_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("CONICAL_SURFACE(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, position) = param_from_chunks::<usize>(false, s, &mut i, strs)?;
        let (s, radius) = param_from_chunks::<f64>(false, s, &mut i, strs)?;
        let (s, semi_angle) = param_from_chunks::<f64>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                position,
                radius,
                semi_angle,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct SphericalSurface_<'a> {
    pub name: &'a str,
    pub position: usize,
    pub radius: f64,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> SphericalSurface_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("SPHERICAL_SURFACE(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, position) = param_from_chunks::<usize>(false, s, &mut i, strs)?;
        let (s, radius) = param_from_chunks::<f64>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                position,
                radius,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct ToroidalSurface_<'a> {
    pub name: &'a str,
    pub position: usize,
    pub major_radius: f64,
    pub minor_radius: f64,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> ToroidalSurface_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("TOROIDAL_SURFACE(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, position) = param_from_chunks::<usize>(false, s, &mut i, strs)?;
        let (s, major_radius) = param_from_chunks::<f64>(false, s, &mut i, strs)?;
        let (s, minor_radius) = param_from_chunks::<f64>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                position,
                major_radius,
                minor_radius,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct BSplineSurfaceWithKnots_<'a> {
    pub name: &'a str,
    pub u_degree: i64,
    pub v_degree: i64,
    pub control_points_list: Vec<Vec<usize>>,
    pub surface_form: &'a str,
    pub u_closed: Logical,
    pub v_closed: Logical,
    pub self_intersect: Logical,
    pub u_multiplicities: Vec<i64>,
    pub v_multiplicities: Vec<i64>,
    pub u_knots: Vec<f64>,
    pub v_knots: Vec<f64>,
    pub knot_spec: &'a str,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> BSplineSurfaceWithKnots_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("B_SPLINE_SURFACE_WITH_KNOTS(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, u_degree) = param_from_chunks::<i64>(false, s, &mut i, strs)?;
        let (s, v_degree) = param_from_chunks::<i64>(false, s, &mut i, strs)?;
        let (s, control_points_list) =
            param_from_chunks::<Vec<Vec<usize>>>(false, s, &mut i, strs)?;
        let (s, surface_form) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, u_closed) = param_from_chunks::<Logical>(false, s, &mut i, strs)?;
        let (s, v_closed) = param_from_chunks::<Logical>(false, s, &mut i, strs)?;
        let (s, self_intersect) = param_from_chunks::<Logical>(false, s, &mut i, strs)?;
        let (s, u_multiplicities) = param_from_chunks::<Vec<i64>>(false, s, &mut i, strs)?;
        let (s, v_multiplicities) = param_from_chunks::<Vec<i64>>(false, s, &mut i, strs)?;
        let (s, u_knots) = param_from_chunks::<Vec<f64>>(false, s, &mut i, strs)?;
        let (s, v_knots) = param_from_chunks::<Vec<f64>>(false, s, &mut i, strs)?;
        let (s, knot_spec) = param_from_chunks::<&'a str>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                u_degree,
                v_degree,
                control_points_list,
                surface_form,
                u_closed,
                v_closed,
                self_intersect,
                u_multiplicities,
                v_multiplicities,
                u_knots,
                v_knots,
                knot_spec,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct RationalBSplineSurface_<'a> {
    pub name: &'a str,
    pub u_degree: i64,
    pub v_degree: i64,
    pub control_points_list: Vec<Vec<usize>>,
    pub surface_form: &'a str,
    pub u_closed: Logical,
    pub v_closed: Logical,
    pub self_intersect: Logical,
    pub weights_data: Vec<Vec<f64>>,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> RationalBSplineSurface_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("RATIONAL_B_SPLINE_SURFACE(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, u_degree) = param_from_chunks::<i64>(false, s, &mut i, strs)?;
        let (s, v_degree) = param_from_chunks::<i64>(false, s, &mut i, strs)?;
        let (s, control_points_list) =
            param_from_chunks::<Vec<Vec<usize>>>(false, s, &mut i, strs)?;
        let (s, surface_form) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, u_closed) = param_from_chunks::<Logical>(false, s, &mut i, strs)?;
        let (s, v_closed) = param_from_chunks::<Logical>(false, s, &mut i, strs)?;
        let (s, self_intersect) = param_from_chunks::<Logical>(false, s, &mut i, strs)?;
        let (s, weights_data) = param_from_chunks::<Vec<Vec<f64>>>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                u_degree,
                v_degree,
                control_points_list,
                surface_form,
                u_closed,
                v_closed,
                self_intersect,
                weights_data,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct VertexPoint_<'a> {
    pub representation_item__name: &'a str,
    pub vertex_geometry: usize,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> VertexPoint_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("VERTEX_POINT(")(strs[0])?;
        let (s, representation_item__name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, vertex_geometry) = param_from_chunks::<usize>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                representation_item__name,
                vertex_geometry,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct EdgeCurve_<'a> {
    pub representation_item__name: &'a str,
    pub edge_start: usize,
    pub edge_end: usize,
    pub edge_geometry: usize,
    pub same_sense: bool,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> EdgeCurve_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("EDGE_CURVE(")(strs[0])?;
        let (s, representation_item__name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, edge_start) = param_from_chunks::<usize>(false, s, &mut i, strs)?;
        let (s, edge_end) = param_from_chunks::<usize>(false, s, &mut i, strs)?;
        let (s, edge_geometry) = param_from_chunks::<usize>(false, s, &mut i, strs)?;
        let (s, same_sense) = param_from_chunks::<bool>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                representation_item__name,
                edge_start,
                edge_end,
                edge_geometry,
                same_sense,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct OrientedEdge_<'a> {
    pub name: &'a str,
    pub edge_element: usize,
    pub orientation: bool,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> OrientedEdge_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("ORIENTED_EDGE(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, _) = param_from_chunks::<Derived>(false, s, &mut i, strs)?;
        let (s, _) = param_from_chunks::<Derived>(false, s, &mut i, strs)?;
        let (s, edge_element) = param_from_chunks::<usize>(false, s, &mut i, strs)?;
        let (s, orientation) = param_from_chunks::<bool>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                edge_element,
                orientation,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct EdgeLoop_<'a> {
    pub representation_item__name: &'a str,
    pub edge_list: Vec<usize>,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> EdgeLoop_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("EDGE_LOOP(")(strs[0])?;
        let (s, representation_item__name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, edge_list) = param_from_chunks::<Vec<usize>>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                representation_item__name,
                edge_list,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct FaceBound_<'a> {
    pub name: &'a str,
    pub bound: usize,
    pub orientation: bool,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> FaceBound_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("FACE_BOUND(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, bound) = param_from_chunks::<usize>(false, s, &mut i, strs)?;
        let (s, orientation) = param_from_chunks::<bool>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                bound,
                orientation,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct FaceOuterBound_<'a> {
    pub name: &'a str,
    pub bound: usize,
    pub orientation: bool,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> FaceOuterBound_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("FACE_OUTER_BOUND(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, bound) = param_from_chunks::<usize>(false, s, &mut i, strs)?;
        let (s, orientation) = param_from_chunks::<bool>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                bound,
                orientation,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct AdvancedFace_<'a> {
    pub name: &'a str,
    pub bounds: Vec<usize>,
    pub face_geometry: usize,
    pub same_sense: bool,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> AdvancedFace_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("ADVANCED_FACE(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, bounds) = param_from_chunks::<Vec<usize>>(false, s, &mut i, strs)?;
        let (s, face_geometry) = param_from_chunks::<usize>(false, s, &mut i, strs)?;
        let (s, same_sense) = param_from_chunks::<bool>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                bounds,
                face_geometry,
                same_sense,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct ClosedShell_<'a> {
    pub name: &'a str,
    pub cfs_faces: Vec<usize>,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> ClosedShell_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("CLOSED_SHELL(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, cfs_faces) = param_from_chunks::<Vec<usize>>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                cfs_faces,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct ManifoldSolidBrep_<'a> {
    pub name: &'a str,
    pub outer: usize,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> ManifoldSolidBrep_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("MANIFOLD_SOLID_BREP(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, outer) = param_from_chunks::<usize>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                outer,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct ShapeRepresentation_<'a> {
    pub name: &'a str,
    pub items: Vec<usize>,
    pub context_of_items: usize,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> ShapeRepresentation_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("SHAPE_REPRESENTATION(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, items) = param_from_chunks::<Vec<usize>>(false, s, &mut i, strs)?;
        let (s, context_of_items) = param_from_chunks::<usize>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                items,
                context_of_items,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct AdvancedBrepShapeRepresentation_<'a> {
    pub name: &'a str,
    pub items: Vec<usize>,
    pub context_of_items: usize,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> AdvancedBrepShapeRepresentation_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("ADVANCED_BREP_SHAPE_REPRESENTATION(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, items) = param_from_chunks::<Vec<usize>>(false, s, &mut i, strs)?;
        let (s, context_of_items) = param_from_chunks::<usize>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                items,
                context_of_items,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct RepresentationRelationshipWithTransformation_<'a> {
    pub name: &'a str,
    pub description: Option<&'a str>,
    pub rep_1: usize,
    pub rep_2: usize,
    pub transformation_operator: usize,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> RepresentationRelationshipWithTransformation_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("REPRESENTATION_RELATIONSHIP_WITH_TRANSFORMATION(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, description) = param_from_chunks::<Option<&'a str>>(false, s, &mut i, strs)?;
        let (s, rep_1) = param_from_chunks::<usize>(false, s, &mut i, strs)?;
        let (s, rep_2) = param_from_chunks::<usize>(false, s, &mut i, strs)?;
        let (s, transformation_operator) = param_from_chunks::<usize>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                description,
                rep_1,
                rep_2,
                transformation_operator,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct ShapeRepresentationRelationship_<'a> {
    pub name: &'a str,
    pub description: Option<&'a str>,
    pub rep_1: usize,
    pub rep_2: usize,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> ShapeRepresentationRelationship_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("SHAPE_REPRESENTATION_RELATIONSHIP(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, description) = param_from_chunks::<Option<&'a str>>(false, s, &mut i, strs)?;
        let (s, rep_1) = param_from_chunks::<usize>(false, s, &mut i, strs)?;
        let (s, rep_2) = param_from_chunks::<usize>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                description,
                rep_1,
                rep_2,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct ItemDefinedTransformation_<'a> {
    pub name: &'a str,
    pub description: Option<&'a str>,
    pub transform_item_1: usize,
    pub transform_item_2: usize,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> ItemDefinedTransformation_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("ITEM_DEFINED_TRANSFORMATION(")(strs[0])?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, description) = param_from_chunks::<Option<&'a str>>(false, s, &mut i, strs)?;
        let (s, transform_item_1) = param_from_chunks::<usize>(false, s, &mut i, strs)?;
        let (s, transform_item_2) = param_from_chunks::<usize>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                description,
                transform_item_1,
                transform_item_2,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct SiUnit_<'a> {
    pub prefix: Option<&'a str>,
    pub name: &'a str,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> SiUnit_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("SI_UNIT(")(strs[0])?;
        let (s, _) = param_from_chunks::<Derived>(false, s, &mut i, strs)?;
        let (s, prefix) = param_from_chunks::<Option<&'a str>>(false, s, &mut i, strs)?;
        let (s, name) = param_from_chunks::<&'a str>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                prefix,
                name,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct ConversionBasedUnit_<'a> {
    pub name: &'a str,
    pub conversion_factor: usize,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> ConversionBasedUnit_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("CONVERSION_BASED_UNIT(")(strs[0])?;
        let (s, _) = param_from_chunks::<Derived>(false, s, &mut i, strs)?;
        let (s, name) = param_from_chunks::<&'a str>(false, s, &mut i, strs)?;
        let (s, conversion_factor) = param_from_chunks::<usize>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                name,
                conversion_factor,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub struct LengthUnit_<'a> {
    pub dimensions: usize,
    _p: std::marker::PhantomData<&'a ()>,
}
impl<'a> LengthUnit_<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let mut i = 0;
        let (s, _) = tag("LENGTH_UNIT(")(strs[0])?;
        let (s, dimensions) = param_from_chunks::<usize>(true, s, &mut i, strs)?;
        Ok((
            s,
            Self {
                dimensions,
                _p: std::marker::PhantomData,
            },
        ))
    }
}

#[derive(Debug)]
pub enum Entity<'a> {
    CartesianPoint(CartesianPoint_<'a>),
    Direction(Direction_<'a>),
    Vector(Vector_<'a>),
    Axis2Placement3d(Axis2Placement3d_<'a>),
    Line(Line_<'a>),
    Circle(Circle_<'a>),
    Ellipse(Ellipse_<'a>),
    BSplineCurve(BSplineCurve_<'a>),
    BSplineCurveWithKnots(BSplineCurveWithKnots_<'a>),
    RationalBSplineCurve(RationalBSplineCurve_<'a>),
    Plane(Plane_<'a>),
    CylindricalSurface(CylindricalSurface_<'a>),
    ConicalSurface(ConicalSurface_<'a>),
    SphericalSurface(SphericalSurface_<'a>),
    ToroidalSurface(ToroidalSurface_<'a>),
    BSplineSurfaceWithKnots(BSplineSurfaceWithKnots_<'a>),
    RationalBSplineSurface(RationalBSplineSurface_<'a>),
    VertexPoint(VertexPoint_<'a>),
    EdgeCurve(EdgeCurve_<'a>),
    OrientedEdge(OrientedEdge_<'a>),
    EdgeLoop(EdgeLoop_<'a>),
    FaceBound(FaceBound_<'a>),
    FaceOuterBound(FaceOuterBound_<'a>),
    AdvancedFace(AdvancedFace_<'a>),
    ClosedShell(ClosedShell_<'a>),
    ManifoldSolidBrep(ManifoldSolidBrep_<'a>),
    ShapeRepresentation(ShapeRepresentation_<'a>),
    AdvancedBrepShapeRepresentation(AdvancedBrepShapeRepresentation_<'a>),
    RepresentationRelationshipWithTransformation(RepresentationRelationshipWithTransformation_<'a>),
    ShapeRepresentationRelationship(ShapeRepresentationRelationship_<'a>),
    ItemDefinedTransformation(ItemDefinedTransformation_<'a>),
    SiUnit(SiUnit_<'a>),
    ConversionBasedUnit(ConversionBasedUnit_<'a>),
    LengthUnit(LengthUnit_<'a>),
    /// Unparsed entity — tag extracted, payload left as raw str.
    Generic(&'a str),
    ComplexEntity(Vec<Entity<'a>>),
    _FailedToParse,
    _EmptySlot,
}

impl<'a> Entity<'a> {
    pub fn parse_chunks(strs: &[&'a str]) -> IResult<'a, Self> {
        let (_, r) = recognize(pair(
            nom::branch::alt((alpha0, tag("_"))),
            many0(nom::branch::alt((alphanumeric1, tag("_")))),
        ))(strs[0])?;
        match r {
            "CARTESIAN_POINT" => {
                CartesianPoint_::parse_chunks(strs).map(|(s, v)| (s, Entity::CartesianPoint(v)))
            }
            "DIRECTION" => Direction_::parse_chunks(strs).map(|(s, v)| (s, Entity::Direction(v))),
            "VECTOR" => Vector_::parse_chunks(strs).map(|(s, v)| (s, Entity::Vector(v))),
            "AXIS2_PLACEMENT_3D" => {
                Axis2Placement3d_::parse_chunks(strs).map(|(s, v)| (s, Entity::Axis2Placement3d(v)))
            }
            "LINE" => Line_::parse_chunks(strs).map(|(s, v)| (s, Entity::Line(v))),
            "CIRCLE" => Circle_::parse_chunks(strs).map(|(s, v)| (s, Entity::Circle(v))),
            "ELLIPSE" => Ellipse_::parse_chunks(strs).map(|(s, v)| (s, Entity::Ellipse(v))),
            "B_SPLINE_CURVE" => {
                BSplineCurve_::parse_chunks(strs).map(|(s, v)| (s, Entity::BSplineCurve(v)))
            }
            "B_SPLINE_CURVE_WITH_KNOTS" => BSplineCurveWithKnots_::parse_chunks(strs)
                .map(|(s, v)| (s, Entity::BSplineCurveWithKnots(v))),
            "RATIONAL_B_SPLINE_CURVE" => RationalBSplineCurve_::parse_chunks(strs)
                .map(|(s, v)| (s, Entity::RationalBSplineCurve(v))),
            "PLANE" => Plane_::parse_chunks(strs).map(|(s, v)| (s, Entity::Plane(v))),
            "CYLINDRICAL_SURFACE" => CylindricalSurface_::parse_chunks(strs)
                .map(|(s, v)| (s, Entity::CylindricalSurface(v))),
            "CONICAL_SURFACE" => {
                ConicalSurface_::parse_chunks(strs).map(|(s, v)| (s, Entity::ConicalSurface(v)))
            }
            "SPHERICAL_SURFACE" => {
                SphericalSurface_::parse_chunks(strs).map(|(s, v)| (s, Entity::SphericalSurface(v)))
            }
            "TOROIDAL_SURFACE" => {
                ToroidalSurface_::parse_chunks(strs).map(|(s, v)| (s, Entity::ToroidalSurface(v)))
            }
            "B_SPLINE_SURFACE_WITH_KNOTS" => BSplineSurfaceWithKnots_::parse_chunks(strs)
                .map(|(s, v)| (s, Entity::BSplineSurfaceWithKnots(v))),
            "RATIONAL_B_SPLINE_SURFACE" => RationalBSplineSurface_::parse_chunks(strs)
                .map(|(s, v)| (s, Entity::RationalBSplineSurface(v))),
            "VERTEX_POINT" => {
                VertexPoint_::parse_chunks(strs).map(|(s, v)| (s, Entity::VertexPoint(v)))
            }
            "EDGE_CURVE" => EdgeCurve_::parse_chunks(strs).map(|(s, v)| (s, Entity::EdgeCurve(v))),
            "ORIENTED_EDGE" => {
                OrientedEdge_::parse_chunks(strs).map(|(s, v)| (s, Entity::OrientedEdge(v)))
            }
            "EDGE_LOOP" => EdgeLoop_::parse_chunks(strs).map(|(s, v)| (s, Entity::EdgeLoop(v))),
            "FACE_BOUND" => FaceBound_::parse_chunks(strs).map(|(s, v)| (s, Entity::FaceBound(v))),
            "FACE_OUTER_BOUND" => {
                FaceOuterBound_::parse_chunks(strs).map(|(s, v)| (s, Entity::FaceOuterBound(v)))
            }
            "ADVANCED_FACE" => {
                AdvancedFace_::parse_chunks(strs).map(|(s, v)| (s, Entity::AdvancedFace(v)))
            }
            "CLOSED_SHELL" => {
                ClosedShell_::parse_chunks(strs).map(|(s, v)| (s, Entity::ClosedShell(v)))
            }
            "MANIFOLD_SOLID_BREP" => ManifoldSolidBrep_::parse_chunks(strs)
                .map(|(s, v)| (s, Entity::ManifoldSolidBrep(v))),
            "SHAPE_REPRESENTATION" => ShapeRepresentation_::parse_chunks(strs)
                .map(|(s, v)| (s, Entity::ShapeRepresentation(v))),
            "ADVANCED_BREP_SHAPE_REPRESENTATION" => {
                AdvancedBrepShapeRepresentation_::parse_chunks(strs)
                    .map(|(s, v)| (s, Entity::AdvancedBrepShapeRepresentation(v)))
            }
            "REPRESENTATION_RELATIONSHIP_WITH_TRANSFORMATION" => {
                RepresentationRelationshipWithTransformation_::parse_chunks(strs)
                    .map(|(s, v)| (s, Entity::RepresentationRelationshipWithTransformation(v)))
            }
            "SHAPE_REPRESENTATION_RELATIONSHIP" => {
                ShapeRepresentationRelationship_::parse_chunks(strs)
                    .map(|(s, v)| (s, Entity::ShapeRepresentationRelationship(v)))
            }
            "ITEM_DEFINED_TRANSFORMATION" => ItemDefinedTransformation_::parse_chunks(strs)
                .map(|(s, v)| (s, Entity::ItemDefinedTransformation(v))),
            "SI_UNIT" => SiUnit_::parse_chunks(strs).map(|(s, v)| (s, Entity::SiUnit(v))),
            "CONVERSION_BASED_UNIT" => ConversionBasedUnit_::parse_chunks(strs)
                .map(|(s, v)| (s, Entity::ConversionBasedUnit(v))),
            "LENGTH_UNIT" => {
                LengthUnit_::parse_chunks(strs).map(|(s, v)| (s, Entity::LengthUnit(v)))
            }
            "" => parse_complex_mapping(strs[0]),
            _ => Ok(("", Entity::Generic(strs[0]))),
        }
    }
}

impl<'a> Parse<'a> for Entity<'a> {
    fn parse(s: &'a str) -> IResult<'a, Self> {
        Self::parse_chunks(&[s])
    }
}

pub fn superclasses_of(s: &str) -> &[&str] {
    match s {
        "ABS_FUNCTION" => &["UNARY_FUNCTION_CALL"],
        "ACOS_FUNCTION" => &["UNARY_FUNCTION_CALL"],
        "ADVANCED_BREP_SHAPE_REPRESENTATION" => &["SHAPE_REPRESENTATION"],
        "ADVANCED_FACE" => &["FACE_SURFACE"],
        "AMOUNT_OF_SUBSTANCE_MEASURE_WITH_UNIT" => &["MEASURE_WITH_UNIT"],
        "AMOUNT_OF_SUBSTANCE_UNIT" => &["NAMED_UNIT"],
        "AND_EXPRESSION" => &["MULTIPLE_ARITY_BOOLEAN_EXPRESSION"],
        "ANGULAR_DIMENSION" => &["DIMENSION_CURVE_DIRECTED_CALLOUT"],
        "ANGULAR_LOCATION" => &["DIMENSIONAL_LOCATION"],
        "ANGULAR_SIZE" => &["DIMENSIONAL_SIZE"],
        "ANGULARITY_TOLERANCE" => &["GEOMETRIC_TOLERANCE_WITH_DATUM_REFERENCE"],
        "ANNOTATION_CURVE_OCCURRENCE" => &["ANNOTATION_OCCURRENCE"],
        "ANNOTATION_FILL_AREA" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "ANNOTATION_FILL_AREA_OCCURRENCE" => &["ANNOTATION_OCCURRENCE"],
        "ANNOTATION_OCCURRENCE" => &["STYLED_ITEM"],
        "ANNOTATION_OCCURRENCE_ASSOCIATIVITY" => &["ANNOTATION_OCCURRENCE_RELATIONSHIP"],
        "ANNOTATION_PLANE" => &["ANNOTATION_OCCURRENCE", "GEOMETRIC_REPRESENTATION_ITEM"],
        "ANNOTATION_SUBFIGURE_OCCURRENCE" => &["ANNOTATION_SYMBOL_OCCURRENCE"],
        "ANNOTATION_SYMBOL" => &["MAPPED_ITEM"],
        "ANNOTATION_SYMBOL_OCCURRENCE" => &["ANNOTATION_OCCURRENCE"],
        "ANNOTATION_TEXT" => &["MAPPED_ITEM"],
        "ANNOTATION_TEXT_CHARACTER" => &["MAPPED_ITEM"],
        "ANNOTATION_TEXT_OCCURRENCE" => &["ANNOTATION_OCCURRENCE"],
        "APEX" => &["DERIVED_SHAPE_ASPECT"],
        "APPLIED_ACTION_ASSIGNMENT" => &["ACTION_ASSIGNMENT"],
        "APPLIED_ACTION_REQUEST_ASSIGNMENT" => &["ACTION_REQUEST_ASSIGNMENT"],
        "APPLIED_APPROVAL_ASSIGNMENT" => &["APPROVAL_ASSIGNMENT"],
        "APPLIED_AREA" => &["SHAPE_ASPECT"],
        "APPLIED_CERTIFICATION_ASSIGNMENT" => &["CERTIFICATION_ASSIGNMENT"],
        "APPLIED_CLASSIFICATION_ASSIGNMENT" => &["CLASSIFICATION_ASSIGNMENT"],
        "APPLIED_CONTRACT_ASSIGNMENT" => &["CONTRACT_ASSIGNMENT"],
        "APPLIED_DATE_AND_TIME_ASSIGNMENT" => &["DATE_AND_TIME_ASSIGNMENT"],
        "APPLIED_DATE_ASSIGNMENT" => &["DATE_ASSIGNMENT"],
        "APPLIED_DOCUMENT_REFERENCE" => &["DOCUMENT_REFERENCE"],
        "APPLIED_DOCUMENT_USAGE_CONSTRAINT_ASSIGNMENT" => &["DOCUMENT_USAGE_CONSTRAINT_ASSIGNMENT"],
        "APPLIED_EFFECTIVITY_ASSIGNMENT" => &["EFFECTIVITY_ASSIGNMENT"],
        "APPLIED_EVENT_OCCURRENCE_ASSIGNMENT" => &["EVENT_OCCURRENCE_ASSIGNMENT"],
        "APPLIED_EXTERNAL_IDENTIFICATION_ASSIGNMENT" => &["EXTERNAL_IDENTIFICATION_ASSIGNMENT"],
        "APPLIED_GROUP_ASSIGNMENT" => &["GROUP_ASSIGNMENT"],
        "APPLIED_IDENTIFICATION_ASSIGNMENT" => &["IDENTIFICATION_ASSIGNMENT"],
        "APPLIED_INEFFECTIVITY_ASSIGNMENT" => &["EFFECTIVITY_ASSIGNMENT"],
        "APPLIED_NAME_ASSIGNMENT" => &["NAME_ASSIGNMENT"],
        "APPLIED_ORGANIZATION_ASSIGNMENT" => &["ORGANIZATION_ASSIGNMENT"],
        "APPLIED_ORGANIZATIONAL_PROJECT_ASSIGNMENT" => &["ORGANIZATIONAL_PROJECT_ASSIGNMENT"],
        "APPLIED_PERSON_AND_ORGANIZATION_ASSIGNMENT" => &["PERSON_AND_ORGANIZATION_ASSIGNMENT"],
        "APPLIED_PRESENTED_ITEM" => &["PRESENTED_ITEM"],
        "APPLIED_SECURITY_CLASSIFICATION_ASSIGNMENT" => &["SECURITY_CLASSIFICATION_ASSIGNMENT"],
        "APPLIED_TIME_INTERVAL_ASSIGNMENT" => &["TIME_INTERVAL_ASSIGNMENT"],
        "APPROXIMATION_TOLERANCE" => &["FOUNDED_ITEM"],
        "APPROXIMATION_TOLERANCE_DEVIATION" => &["FOUNDED_ITEM"],
        "APPROXIMATION_TOLERANCE_PARAMETER" => &["FOUNDED_ITEM"],
        "AREA_MEASURE_WITH_UNIT" => &["MEASURE_WITH_UNIT"],
        "AREA_UNIT" => &["DERIVED_UNIT"],
        "ASIN_FUNCTION" => &["UNARY_FUNCTION_CALL"],
        "ASSEMBLY_COMPONENT_USAGE" => &["PRODUCT_DEFINITION_USAGE"],
        "ATAN_FUNCTION" => &["BINARY_FUNCTION_CALL"],
        "ATTRIBUTE_LANGUAGE_ASSIGNMENT" => &["ATTRIBUTE_CLASSIFICATION_ASSIGNMENT"],
        "AXIS1_PLACEMENT" => &["PLACEMENT"],
        "AXIS2_PLACEMENT_2D" => &["PLACEMENT"],
        "AXIS2_PLACEMENT_3D" => &["PLACEMENT"],
        "B_SPLINE_CURVE" => &["BOUNDED_CURVE"],
        "B_SPLINE_CURVE_WITH_KNOTS" => &["B_SPLINE_CURVE"],
        "B_SPLINE_SURFACE" => &["BOUNDED_SURFACE"],
        "B_SPLINE_SURFACE_WITH_KNOTS" => &["B_SPLINE_SURFACE"],
        "BACKGROUND_COLOUR" => &["COLOUR"],
        "BARRING_HOLE" => &["FEATURE_DEFINITION"],
        "BEAD" => &["FEATURE_DEFINITION"],
        "BEAD_END" => &["SHAPE_ASPECT"],
        "BEZIER_CURVE" => &["B_SPLINE_CURVE"],
        "BEZIER_SURFACE" => &["B_SPLINE_SURFACE"],
        "BINARY_BOOLEAN_EXPRESSION" => &["BOOLEAN_EXPRESSION", "BINARY_GENERIC_EXPRESSION"],
        "BINARY_FUNCTION_CALL" => &["BINARY_NUMERIC_EXPRESSION"],
        "BINARY_GENERIC_EXPRESSION" => &["GENERIC_EXPRESSION"],
        "BINARY_NUMERIC_EXPRESSION" => &["NUMERIC_EXPRESSION", "BINARY_GENERIC_EXPRESSION"],
        "BLOCK" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "BOOLEAN_DEFINED_FUNCTION" => &["DEFINED_FUNCTION", "BOOLEAN_EXPRESSION"],
        "BOOLEAN_EXPRESSION" => &["EXPRESSION"],
        "BOOLEAN_LITERAL" => &["SIMPLE_BOOLEAN_EXPRESSION", "GENERIC_LITERAL"],
        "BOOLEAN_RESULT" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "BOOLEAN_VARIABLE" => &["SIMPLE_BOOLEAN_EXPRESSION", "VARIABLE"],
        "BOSS" => &["FEATURE_DEFINITION"],
        "BOSS_TOP" => &["SHAPE_ASPECT"],
        "BOUNDARY_CURVE" => &["COMPOSITE_CURVE_ON_SURFACE"],
        "BOUNDED_CURVE" => &["CURVE"],
        "BOUNDED_PCURVE" => &["PCURVE", "BOUNDED_CURVE"],
        "BOUNDED_SURFACE" => &["SURFACE"],
        "BOUNDED_SURFACE_CURVE" => &["SURFACE_CURVE", "BOUNDED_CURVE"],
        "BOX_DOMAIN" => &["FOUNDED_ITEM"],
        "BOXED_HALF_SPACE" => &["HALF_SPACE_SOLID"],
        "BREP_WITH_VOIDS" => &["MANIFOLD_SOLID_BREP"],
        "CALENDAR_DATE" => &["DATE"],
        "CAMERA_IMAGE" => &["MAPPED_ITEM"],
        "CAMERA_IMAGE_2D_WITH_SCALE" => &["CAMERA_IMAGE"],
        "CAMERA_IMAGE_3D_WITH_SCALE" => &["CAMERA_IMAGE"],
        "CAMERA_MODEL" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "CAMERA_MODEL_D2" => &["CAMERA_MODEL"],
        "CAMERA_MODEL_D3" => &["CAMERA_MODEL"],
        "CAMERA_MODEL_D3_WITH_HLHSR" => &["CAMERA_MODEL_D3"],
        "CAMERA_USAGE" => &["REPRESENTATION_MAP"],
        "CARTESIAN_POINT" => &["POINT"],
        "CARTESIAN_TRANSFORMATION_OPERATOR" => &[
            "GEOMETRIC_REPRESENTATION_ITEM",
            "FUNCTIONALLY_DEFINED_TRANSFORMATION",
        ],
        "CARTESIAN_TRANSFORMATION_OPERATOR_2D" => &["CARTESIAN_TRANSFORMATION_OPERATOR"],
        "CARTESIAN_TRANSFORMATION_OPERATOR_3D" => &["CARTESIAN_TRANSFORMATION_OPERATOR"],
        "CELSIUS_TEMPERATURE_MEASURE_WITH_UNIT" => &["MEASURE_WITH_UNIT"],
        "CENTRE_OF_SYMMETRY" => &["DERIVED_SHAPE_ASPECT"],
        "CHAMFER" => &["TRANSITION_FEATURE"],
        "CHAMFER_OFFSET" => &["SHAPE_ASPECT"],
        "CHARACTER_GLYPH_SYMBOL" => &["GENERIC_CHARACTER_GLYPH_SYMBOL"],
        "CHARACTERIZED_CLASS" => &["CHARACTERIZED_OBJECT", "CLASS"],
        "CIRCLE" => &["CONIC"],
        "CIRCULAR_CLOSED_PROFILE" => &["SHAPE_ASPECT"],
        "CIRCULAR_PATTERN" => &["REPLICATE_FEATURE"],
        "CIRCULAR_RUNOUT_TOLERANCE" => &["GEOMETRIC_TOLERANCE_WITH_DATUM_REFERENCE"],
        "CLASS" => &["GROUP"],
        "CLASS_SYSTEM" => &["GROUP"],
        "CLASS_USAGE_EFFECTIVITY_CONTEXT_ASSIGNMENT" => &["EFFECTIVITY_CONTEXT_ASSIGNMENT"],
        "CLOSED_PATH_PROFILE" => &["SHAPE_ASPECT"],
        "CLOSED_SHELL" => &["CONNECTED_FACE_SET"],
        "COAXIALITY_TOLERANCE" => &["GEOMETRIC_TOLERANCE_WITH_DATUM_REFERENCE"],
        "COLOUR_RGB" => &["COLOUR_SPECIFICATION"],
        "COLOUR_SPECIFICATION" => &["COLOUR"],
        "COMMON_DATUM" => &["COMPOSITE_SHAPE_ASPECT", "DATUM"],
        "COMPARISON_EQUAL" => &["COMPARISON_EXPRESSION"],
        "COMPARISON_EXPRESSION" => &["BOOLEAN_EXPRESSION", "BINARY_GENERIC_EXPRESSION"],
        "COMPARISON_GREATER" => &["COMPARISON_EXPRESSION"],
        "COMPARISON_GREATER_EQUAL" => &["COMPARISON_EXPRESSION"],
        "COMPARISON_LESS" => &["COMPARISON_EXPRESSION"],
        "COMPARISON_LESS_EQUAL" => &["COMPARISON_EXPRESSION"],
        "COMPARISON_NOT_EQUAL" => &["COMPARISON_EXPRESSION"],
        "COMPOSITE_CURVE" => &["BOUNDED_CURVE"],
        "COMPOSITE_CURVE_ON_SURFACE" => &["COMPOSITE_CURVE"],
        "COMPOSITE_CURVE_SEGMENT" => &["FOUNDED_ITEM"],
        "COMPOSITE_HOLE" => &["COMPOUND_FEATURE"],
        "COMPOSITE_SHAPE_ASPECT" => &["SHAPE_ASPECT"],
        "COMPOSITE_TEXT" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "COMPOSITE_TEXT_WITH_ASSOCIATED_CURVES" => &["COMPOSITE_TEXT"],
        "COMPOSITE_TEXT_WITH_BLANKING_BOX" => &["COMPOSITE_TEXT"],
        "COMPOSITE_TEXT_WITH_EXTENT" => &["COMPOSITE_TEXT"],
        "COMPOUND_FEATURE" => &["FEATURE_DEFINITION"],
        "COMPOUND_REPRESENTATION_ITEM" => &["REPRESENTATION_ITEM"],
        "COMPOUND_SHAPE_REPRESENTATION" => &["SHAPE_REPRESENTATION"],
        "CONCAT_EXPRESSION" => &["STRING_EXPRESSION", "MULTIPLE_ARITY_GENERIC_EXPRESSION"],
        "CONCENTRICITY_TOLERANCE" => &["GEOMETRIC_TOLERANCE_WITH_DATUM_REFERENCE"],
        "CONCEPT_FEATURE_RELATIONSHIP_WITH_CONDITION" => &["CONCEPT_FEATURE_RELATIONSHIP"],
        "CONDITIONAL_CONCEPT_FEATURE" => &["PRODUCT_CONCEPT_FEATURE"],
        "CONFIGURABLE_ITEM" => &["CONFIGURATION_ITEM"],
        "CONFIGURATION_EFFECTIVITY" => &["PRODUCT_DEFINITION_EFFECTIVITY"],
        "CONFIGURED_EFFECTIVITY_ASSIGNMENT" => &["EFFECTIVITY_ASSIGNMENT"],
        "CONFIGURED_EFFECTIVITY_CONTEXT_ASSIGNMENT" => &["EFFECTIVITY_CONTEXT_ASSIGNMENT"],
        "CONIC" => &["CURVE"],
        "CONICAL_SURFACE" => &["ELEMENTARY_SURFACE"],
        "CONNECTED_EDGE_SET" => &["TOPOLOGICAL_REPRESENTATION_ITEM"],
        "CONNECTED_FACE_SET" => &["TOPOLOGICAL_REPRESENTATION_ITEM"],
        "CONNECTED_FACE_SUB_SET" => &["CONNECTED_FACE_SET"],
        "CONSTRUCTIVE_GEOMETRY_REPRESENTATION" => &["REPRESENTATION"],
        "CONSTRUCTIVE_GEOMETRY_REPRESENTATION_RELATIONSHIP" => &["REPRESENTATION_RELATIONSHIP"],
        "CONTACT_RATIO_REPRESENTATION" => &["REPRESENTATION"],
        "CONTEXT_DEPENDENT_INVISIBILITY" => &["INVISIBILITY"],
        "CONTEXT_DEPENDENT_OVER_RIDING_STYLED_ITEM" => &["OVER_RIDING_STYLED_ITEM"],
        "CONTEXT_DEPENDENT_UNIT" => &["NAMED_UNIT"],
        "CONVERSION_BASED_UNIT" => &["NAMED_UNIT"],
        "COS_FUNCTION" => &["UNARY_FUNCTION_CALL"],
        "CSG_SHAPE_REPRESENTATION" => &["SHAPE_REPRESENTATION"],
        "CSG_SOLID" => &["SOLID_MODEL"],
        "CURVE" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "CURVE_BOUNDED_SURFACE" => &["BOUNDED_SURFACE"],
        "CURVE_DIMENSION" => &["DIMENSION_CURVE_DIRECTED_CALLOUT"],
        "CURVE_REPLICA" => &["CURVE"],
        "CURVE_STYLE" => &["FOUNDED_ITEM"],
        "CURVE_STYLE_FONT" => &["FOUNDED_ITEM"],
        "CURVE_STYLE_FONT_PATTERN" => &["FOUNDED_ITEM"],
        "CURVE_SWEPT_SOLID_SHAPE_REPRESENTATION" => &["SHAPE_REPRESENTATION"],
        "CYLINDRICAL_PAIR" => &["KINEMATIC_PAIR"],
        "CYLINDRICAL_PAIR_RANGE" => &["SIMPLE_PAIR_RANGE"],
        "CYLINDRICAL_PAIR_VALUE" => &["PAIR_VALUE"],
        "CYLINDRICAL_SURFACE" => &["ELEMENTARY_SURFACE"],
        "CYLINDRICITY_TOLERANCE" => &["GEOMETRIC_TOLERANCE"],
        "DATED_EFFECTIVITY" => &["EFFECTIVITY"],
        "DATUM" => &["SHAPE_ASPECT"],
        "DATUM_FEATURE" => &["SHAPE_ASPECT"],
        "DATUM_FEATURE_CALLOUT" => &["DRAUGHTING_CALLOUT"],
        "DATUM_TARGET" => &["SHAPE_ASPECT"],
        "DATUM_TARGET_CALLOUT" => &["DRAUGHTING_CALLOUT"],
        "DEFAULT_TOLERANCE_TABLE" => &["REPRESENTATION"],
        "DEFAULT_TOLERANCE_TABLE_CELL" => &["COMPOUND_REPRESENTATION_ITEM"],
        "DEFINED_CHARACTER_GLYPH" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "DEFINED_SYMBOL" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "DEFINITIONAL_REPRESENTATION" => &["REPRESENTATION"],
        "DEGENERATE_PCURVE" => &["POINT"],
        "DEGENERATE_TOROIDAL_SURFACE" => &["TOROIDAL_SURFACE"],
        "DERIVED_SHAPE_ASPECT" => &["SHAPE_ASPECT"],
        "DERIVED_UNIT_VARIABLE" => &["DERIVED_UNIT", "VARIABLE_SEMANTICS"],
        "DESCRIPTIVE_REPRESENTATION_ITEM" => &["REPRESENTATION_ITEM"],
        "DIAMETER_DIMENSION" => &["DIMENSION_CURVE_DIRECTED_CALLOUT"],
        "DIMENSION_CALLOUT" => &["DRAUGHTING_CALLOUT"],
        "DIMENSION_CALLOUT_COMPONENT_RELATIONSHIP" => &["DRAUGHTING_CALLOUT_RELATIONSHIP"],
        "DIMENSION_CALLOUT_RELATIONSHIP" => &["DRAUGHTING_CALLOUT_RELATIONSHIP"],
        "DIMENSION_CURVE" => &["ANNOTATION_CURVE_OCCURRENCE"],
        "DIMENSION_CURVE_DIRECTED_CALLOUT" => &["DRAUGHTING_CALLOUT"],
        "DIMENSION_CURVE_TERMINATOR" => &["TERMINATOR_SYMBOL"],
        "DIMENSION_PAIR" => &["DRAUGHTING_CALLOUT_RELATIONSHIP"],
        "DIMENSION_TEXT_ASSOCIATIVITY" => &["TEXT_LITERAL", "MAPPED_ITEM"],
        "DIMENSIONAL_LOCATION" => &["SHAPE_ASPECT_RELATIONSHIP"],
        "DIMENSIONAL_LOCATION_WITH_PATH" => &["DIMENSIONAL_LOCATION"],
        "DIMENSIONAL_SIZE_WITH_PATH" => &["DIMENSIONAL_SIZE"],
        "DIRECTED_ACTION" => &["EXECUTED_ACTION"],
        "DIRECTED_ANGLE" => &["SHAPE_ASPECT"],
        "DIRECTED_DIMENSIONAL_LOCATION" => &["DIMENSIONAL_LOCATION"],
        "DIRECTION" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "DIRECTION_SHAPE_REPRESENTATION" => &["SHAPE_REPRESENTATION"],
        "DIV_EXPRESSION" => &["BINARY_NUMERIC_EXPRESSION"],
        "DOCUMENT_FILE" => &["DOCUMENT", "CHARACTERIZED_OBJECT"],
        "DOCUMENT_PRODUCT_EQUIVALENCE" => &["DOCUMENT_PRODUCT_ASSOCIATION"],
        "DRAUGHTING_ANNOTATION_OCCURRENCE" => &["ANNOTATION_OCCURRENCE"],
        "DRAUGHTING_CALLOUT" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "DRAUGHTING_ELEMENTS" => &["DRAUGHTING_CALLOUT"],
        "DRAUGHTING_MODEL" => &["REPRESENTATION"],
        "DRAUGHTING_MODEL_ITEM_ASSOCIATION" => &["ITEM_IDENTIFIED_REPRESENTATION_USAGE"],
        "DRAUGHTING_PRE_DEFINED_COLOUR" => &["PRE_DEFINED_COLOUR"],
        "DRAUGHTING_PRE_DEFINED_CURVE_FONT" => &["PRE_DEFINED_CURVE_FONT"],
        "DRAUGHTING_PRE_DEFINED_TEXT_FONT" => &["PRE_DEFINED_TEXT_FONT"],
        "DRAUGHTING_SPECIFICATION_REFERENCE" => &["DOCUMENT_REFERENCE"],
        "DRAUGHTING_SUBFIGURE_REPRESENTATION" => &["SYMBOL_REPRESENTATION"],
        "DRAUGHTING_SYMBOL_REPRESENTATION" => &["SYMBOL_REPRESENTATION"],
        "DRAUGHTING_TEXT_LITERAL_WITH_DELINEATION" => &["TEXT_LITERAL_WITH_DELINEATION"],
        "DRAWING_REVISION" => &["PRESENTATION_SET"],
        "DRAWING_SHEET_LAYOUT" => &["DRAUGHTING_SYMBOL_REPRESENTATION"],
        "DRAWING_SHEET_REVISION" => &["PRESENTATION_AREA"],
        "DRAWING_SHEET_REVISION_USAGE" => &["AREA_IN_SET"],
        "EDGE" => &["TOPOLOGICAL_REPRESENTATION_ITEM"],
        "EDGE_BASED_WIREFRAME_MODEL" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "EDGE_BASED_WIREFRAME_SHAPE_REPRESENTATION" => &["SHAPE_REPRESENTATION"],
        "EDGE_CURVE" => &["EDGE", "GEOMETRIC_REPRESENTATION_ITEM"],
        "EDGE_LOOP" => &["LOOP", "PATH"],
        "EDGE_ROUND" => &["TRANSITION_FEATURE"],
        "ELECTRIC_CURRENT_MEASURE_WITH_UNIT" => &["MEASURE_WITH_UNIT"],
        "ELECTRIC_CURRENT_UNIT" => &["NAMED_UNIT"],
        "ELEMENT_DELIVERY" => &["ACTION"],
        "ELEMENTARY_SURFACE" => &["SURFACE"],
        "ELLIPSE" => &["CONIC"],
        "EQUALS_EXPRESSION" => &["BINARY_BOOLEAN_EXPRESSION"],
        "EVALUATED_DEGENERATE_PCURVE" => &["DEGENERATE_PCURVE"],
        "EXCLUSIVE_PRODUCT_CONCEPT_FEATURE_CATEGORY" => &["PRODUCT_CONCEPT_FEATURE_CATEGORY"],
        "EXECUTED_ACTION" => &["ACTION"],
        "EXP_FUNCTION" => &["UNARY_FUNCTION_CALL"],
        "EXPRESSION" => &["GENERIC_EXPRESSION"],
        "EXPRESSION_CONVERSION_BASED_UNIT" => &["CONTEXT_DEPENDENT_UNIT", "VARIABLE_SEMANTICS"],
        "EXTENSION" => &["DERIVED_SHAPE_ASPECT"],
        "EXTERNAL_IDENTIFICATION_ASSIGNMENT" => &["IDENTIFICATION_ASSIGNMENT"],
        "EXTERNALLY_DEFINED_CHARACTER_GLYPH" => &["EXTERNALLY_DEFINED_ITEM"],
        "EXTERNALLY_DEFINED_CLASS" => &["CLASS", "EXTERNALLY_DEFINED_ITEM"],
        "EXTERNALLY_DEFINED_CURVE_FONT" => &["EXTERNALLY_DEFINED_ITEM"],
        "EXTERNALLY_DEFINED_DIMENSION_DEFINITION" => {
            &["DIMENSIONAL_SIZE", "EXTERNALLY_DEFINED_ITEM"]
        }
        "EXTERNALLY_DEFINED_FEATURE_DEFINITION" => {
            &["FEATURE_DEFINITION", "EXTERNALLY_DEFINED_ITEM"]
        }
        "EXTERNALLY_DEFINED_GENERAL_PROPERTY" => &["GENERAL_PROPERTY", "EXTERNALLY_DEFINED_ITEM"],
        "EXTERNALLY_DEFINED_HATCH_STYLE" => {
            &["EXTERNALLY_DEFINED_ITEM", "GEOMETRIC_REPRESENTATION_ITEM"]
        }
        "EXTERNALLY_DEFINED_STYLE" => &["EXTERNALLY_DEFINED_ITEM", "FOUNDED_ITEM"],
        "EXTERNALLY_DEFINED_SYMBOL" => &["EXTERNALLY_DEFINED_ITEM"],
        "EXTERNALLY_DEFINED_TEXT_FONT" => &["EXTERNALLY_DEFINED_ITEM"],
        "EXTERNALLY_DEFINED_TILE_STYLE" => {
            &["EXTERNALLY_DEFINED_ITEM", "GEOMETRIC_REPRESENTATION_ITEM"]
        }
        "EXTRUDED_AREA_SOLID" => &["SWEPT_AREA_SOLID"],
        "EXTRUDED_FACE_SOLID" => &["SWEPT_FACE_SOLID"],
        "FACE" => &["TOPOLOGICAL_REPRESENTATION_ITEM"],
        "FACE_BASED_SURFACE_MODEL" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "FACE_BOUND" => &["TOPOLOGICAL_REPRESENTATION_ITEM"],
        "FACE_OUTER_BOUND" => &["FACE_BOUND"],
        "FACE_SHAPE_REPRESENTATION" => &["SHAPE_REPRESENTATION"],
        "FACE_SURFACE" => &["FACE", "GEOMETRIC_REPRESENTATION_ITEM"],
        "FACETED_BREP" => &["MANIFOLD_SOLID_BREP"],
        "FACETED_BREP_SHAPE_REPRESENTATION" => &["SHAPE_REPRESENTATION"],
        "FEATURE_COMPONENT_DEFINITION" => &["CHARACTERIZED_OBJECT"],
        "FEATURE_COMPONENT_RELATIONSHIP" => &["SHAPE_ASPECT_RELATIONSHIP"],
        "FEATURE_DEFINITION" => &["CHARACTERIZED_OBJECT"],
        "FEATURE_IN_PANEL" => &["FEATURE_DEFINITION"],
        "FEATURE_PATTERN" => &["REPLICATE_FEATURE"],
        "FEATURED_SHAPE" => &["PRODUCT_DEFINITION_SHAPE"],
        "FILL_AREA_STYLE" => &["FOUNDED_ITEM"],
        "FILL_AREA_STYLE_HATCHING" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "FILL_AREA_STYLE_TILE_SYMBOL_WITH_STYLE" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "FILL_AREA_STYLE_TILES" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "FILLET" => &["TRANSITION_FEATURE"],
        "FLATNESS_TOLERANCE" => &["GEOMETRIC_TOLERANCE"],
        "FORMAT_FUNCTION" => &["STRING_EXPRESSION", "BINARY_GENERIC_EXPRESSION"],
        "FOUNDED_KINEMATIC_PATH" => &["REPRESENTATION"],
        "FULLY_CONSTRAINED_PAIR" => &["KINEMATIC_PAIR"],
        "GEAR_PAIR" => &["KINEMATIC_PAIR"],
        "GEAR_PAIR_RANGE" => &["SIMPLE_PAIR_RANGE"],
        "GEAR_PAIR_VALUE" => &["PAIR_VALUE"],
        "GENERAL_FEATURE" => &["FEATURE_DEFINITION"],
        "GENERAL_MATERIAL_PROPERTY" => &["GENERAL_PROPERTY"],
        "GENERIC_CHARACTER_GLYPH_SYMBOL" => &["SYMBOL_REPRESENTATION"],
        "GENERIC_LITERAL" => &["SIMPLE_GENERIC_EXPRESSION"],
        "GENERIC_VARIABLE" => &["SIMPLE_GENERIC_EXPRESSION"],
        "GEOMETRIC_ALIGNMENT" => &["DERIVED_SHAPE_ASPECT"],
        "GEOMETRIC_CURVE_SET" => &["GEOMETRIC_SET"],
        "GEOMETRIC_INTERSECTION" => &["DERIVED_SHAPE_ASPECT"],
        "GEOMETRIC_ITEM_SPECIFIC_USAGE" => &["ITEM_IDENTIFIED_REPRESENTATION_USAGE"],
        "GEOMETRIC_REPRESENTATION_CONTEXT" => &["REPRESENTATION_CONTEXT"],
        "GEOMETRIC_REPRESENTATION_ITEM" => &["REPRESENTATION_ITEM"],
        "GEOMETRIC_SET" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "GEOMETRIC_TOLERANCE_WITH_DATUM_REFERENCE" => &["GEOMETRIC_TOLERANCE"],
        "GEOMETRIC_TOLERANCE_WITH_DEFINED_UNIT" => &["GEOMETRIC_TOLERANCE"],
        "GEOMETRICAL_TOLERANCE_CALLOUT" => &["DRAUGHTING_CALLOUT"],
        "GEOMETRICALLY_BOUNDED_2D_WIREFRAME_REPRESENTATION" => &["SHAPE_REPRESENTATION"],
        "GEOMETRICALLY_BOUNDED_SURFACE_SHAPE_REPRESENTATION" => &["SHAPE_REPRESENTATION"],
        "GEOMETRICALLY_BOUNDED_WIREFRAME_SHAPE_REPRESENTATION" => &["SHAPE_REPRESENTATION"],
        "GLOBAL_UNCERTAINTY_ASSIGNED_CONTEXT" => &["REPRESENTATION_CONTEXT"],
        "GLOBAL_UNIT_ASSIGNED_CONTEXT" => &["REPRESENTATION_CONTEXT"],
        "HALF_SPACE_SOLID" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "HARDNESS_REPRESENTATION" => &["REPRESENTATION"],
        "HIDDEN_ELEMENT_OVER_RIDING_STYLED_ITEM" => &["CONTEXT_DEPENDENT_OVER_RIDING_STYLED_ITEM"],
        "HOLE_BOTTOM" => &["SHAPE_ASPECT"],
        "HOLE_IN_PANEL" => &["FEATURE_DEFINITION"],
        "HOMOKINETIC_PAIR" => &["UNIVERSAL_PAIR"],
        "HYPERBOLA" => &["CONIC"],
        "INCLUSION_PRODUCT_CONCEPT_FEATURE" => &["CONDITIONAL_CONCEPT_FEATURE"],
        "INDEX_EXPRESSION" => &["STRING_EXPRESSION", "BINARY_GENERIC_EXPRESSION"],
        "INSTANCED_FEATURE" => &["SHAPE_ASPECT", "FEATURE_DEFINITION"],
        "INT_LITERAL" => &["LITERAL_NUMBER"],
        "INT_NUMERIC_VARIABLE" => &["NUMERIC_VARIABLE"],
        "INT_VALUE_FUNCTION" => &["VALUE_FUNCTION"],
        "INTEGER_DEFINED_FUNCTION" => &["NUMERIC_DEFINED_FUNCTION"],
        "INTERSECTION_CURVE" => &["SURFACE_CURVE"],
        "INTERVAL_EXPRESSION" => &["BOOLEAN_EXPRESSION", "MULTIPLE_ARITY_GENERIC_EXPRESSION"],
        "JOGGLE" => &["FEATURE_DEFINITION"],
        "JOGGLE_TERMINATION" => &["SHAPE_ASPECT"],
        "KINEMATIC_FRAME_BACKGROUND_REPRESENTATION" => &["REPRESENTATION"],
        "KINEMATIC_FRAME_BACKGROUND_REPRESENTATION_ASSOCIATION" => {
            &["REPRESENTATION_RELATIONSHIP_WITH_TRANSFORMATION"]
        }
        "KINEMATIC_FRAME_BASED_TRANSFORMATION" => &[
            "GEOMETRIC_REPRESENTATION_ITEM",
            "FUNCTIONALLY_DEFINED_TRANSFORMATION",
        ],
        "KINEMATIC_GROUND_REPRESENTATION" => &["REPRESENTATION"],
        "KINEMATIC_LINK_REPRESENTATION" => &["REPRESENTATION"],
        "KINEMATIC_LINK_REPRESENTATION_ASSOCIATION" => &["REPRESENTATION_RELATIONSHIP"],
        "KINEMATIC_PAIR" => &["ITEM_DEFINED_TRANSFORMATION"],
        "KINEMATIC_PATH" => &["REPRESENTATION_ITEM"],
        "KINEMATIC_PROPERTY_DEFINITION" => &["PROPERTY_DEFINITION"],
        "KINEMATIC_PROPERTY_REPRESENTATION_RELATION" => &["PROPERTY_DEFINITION_REPRESENTATION"],
        "KNOWN_SOURCE" => &["EXTERNAL_SOURCE", "PRE_DEFINED_ITEM"],
        "LANGUAGE" => &["GROUP"],
        "LANGUAGE_ASSIGNMENT" => &["CLASSIFICATION_ASSIGNMENT"],
        "LEADER_CURVE" => &["ANNOTATION_CURVE_OCCURRENCE"],
        "LEADER_DIRECTED_CALLOUT" => &["DRAUGHTING_CALLOUT"],
        "LEADER_DIRECTED_DIMENSION" => &["LEADER_DIRECTED_CALLOUT"],
        "LEADER_TERMINATOR" => &["TERMINATOR_SYMBOL"],
        "LENGTH_FUNCTION" => &["NUMERIC_EXPRESSION", "UNARY_GENERIC_EXPRESSION"],
        "LENGTH_MEASURE_WITH_UNIT" => &["MEASURE_WITH_UNIT"],
        "LENGTH_UNIT" => &["NAMED_UNIT"],
        "LIGHT_SOURCE" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "LIGHT_SOURCE_AMBIENT" => &["LIGHT_SOURCE"],
        "LIGHT_SOURCE_DIRECTIONAL" => &["LIGHT_SOURCE"],
        "LIGHT_SOURCE_POSITIONAL" => &["LIGHT_SOURCE"],
        "LIGHT_SOURCE_SPOT" => &["LIGHT_SOURCE"],
        "LIKE_EXPRESSION" => &["COMPARISON_EXPRESSION"],
        "LINE" => &["CURVE"],
        "LINE_PROFILE_TOLERANCE" => &["GEOMETRIC_TOLERANCE"],
        "LINEAR_DIMENSION" => &["DIMENSION_CURVE_DIRECTED_CALLOUT"],
        "LITERAL_NUMBER" => &["SIMPLE_NUMERIC_EXPRESSION", "GENERIC_LITERAL"],
        "LOCATION_SHAPE_REPRESENTATION" => &["SHAPE_REPRESENTATION"],
        "LOCATOR" => &["FEATURE_DEFINITION"],
        "LOG10_FUNCTION" => &["UNARY_FUNCTION_CALL"],
        "LOG2_FUNCTION" => &["UNARY_FUNCTION_CALL"],
        "LOG_FUNCTION" => &["UNARY_FUNCTION_CALL"],
        "LOOP" => &["TOPOLOGICAL_REPRESENTATION_ITEM"],
        "LOT_EFFECTIVITY" => &["EFFECTIVITY"],
        "LUMINOUS_INTENSITY_MEASURE_WITH_UNIT" => &["MEASURE_WITH_UNIT"],
        "LUMINOUS_INTENSITY_UNIT" => &["NAMED_UNIT"],
        "MAKE_FROM_USAGE_OPTION" => &["PRODUCT_DEFINITION_USAGE"],
        "MANIFOLD_SOLID_BREP" => &["SOLID_MODEL"],
        "MANIFOLD_SUBSURFACE_SHAPE_REPRESENTATION" => &["SHAPE_REPRESENTATION"],
        "MANIFOLD_SURFACE_SHAPE_REPRESENTATION" => &["SHAPE_REPRESENTATION"],
        "MAPPED_ITEM" => &["REPRESENTATION_ITEM"],
        "MASS_MEASURE_WITH_UNIT" => &["MEASURE_WITH_UNIT"],
        "MASS_UNIT" => &["NAMED_UNIT"],
        "MATERIAL_PROPERTY" => &["PROPERTY_DEFINITION"],
        "MATERIAL_PROPERTY_REPRESENTATION" => &["PROPERTY_DEFINITION_REPRESENTATION"],
        "MAXIMUM_FUNCTION" => &["MULTIPLE_ARITY_FUNCTION_CALL"],
        "MEASURE_REPRESENTATION_ITEM" => &["REPRESENTATION_ITEM", "MEASURE_WITH_UNIT"],
        "MECHANICAL_DESIGN_GEOMETRIC_PRESENTATION_AREA" => &["PRESENTATION_AREA"],
        "MECHANICAL_DESIGN_GEOMETRIC_PRESENTATION_REPRESENTATION" => &["REPRESENTATION"],
        "MECHANISM_BASE_PLACEMENT" => &["REPRESENTATION_RELATIONSHIP_WITH_TRANSFORMATION"],
        "MINIMUM_FUNCTION" => &["MULTIPLE_ARITY_FUNCTION_CALL"],
        "MINUS_EXPRESSION" => &["BINARY_NUMERIC_EXPRESSION"],
        "MINUS_FUNCTION" => &["UNARY_FUNCTION_CALL"],
        "MOD_EXPRESSION" => &["BINARY_NUMERIC_EXPRESSION"],
        "MODIFIED_GEOMETRIC_TOLERANCE" => &["GEOMETRIC_TOLERANCE"],
        "MODIFIED_PATTERN" => &["REPLICATE_FEATURE"],
        "MOMENTS_OF_INERTIA_REPRESENTATION" => &["REPRESENTATION"],
        "MOTION_LINK_RELATIONSHIP" => &["REPRESENTATION_RELATIONSHIP"],
        "MULT_EXPRESSION" => &["MULTIPLE_ARITY_NUMERIC_EXPRESSION"],
        "MULTI_LANGUAGE_ATTRIBUTE_ASSIGNMENT" => &["ATTRIBUTE_VALUE_ASSIGNMENT"],
        "MULTIPLE_ARITY_BOOLEAN_EXPRESSION" => {
            &["BOOLEAN_EXPRESSION", "MULTIPLE_ARITY_GENERIC_EXPRESSION"]
        }
        "MULTIPLE_ARITY_FUNCTION_CALL" => &["MULTIPLE_ARITY_NUMERIC_EXPRESSION"],
        "MULTIPLE_ARITY_GENERIC_EXPRESSION" => &["GENERIC_EXPRESSION"],
        "MULTIPLE_ARITY_NUMERIC_EXPRESSION" => {
            &["NUMERIC_EXPRESSION", "MULTIPLE_ARITY_GENERIC_EXPRESSION"]
        }
        "NAMED_UNIT_VARIABLE" => &["NAMED_UNIT", "VARIABLE_SEMANTICS"],
        "NEXT_ASSEMBLY_USAGE_OCCURRENCE" => &["ASSEMBLY_COMPONENT_USAGE"],
        "NGON_CLOSED_PROFILE" => &["SHAPE_ASPECT"],
        "NON_MANIFOLD_SURFACE_SHAPE_REPRESENTATION" => &["SHAPE_REPRESENTATION"],
        "NOT_EXPRESSION" => &["UNARY_BOOLEAN_EXPRESSION"],
        "NUMERIC_DEFINED_FUNCTION" => &["NUMERIC_EXPRESSION", "DEFINED_FUNCTION"],
        "NUMERIC_EXPRESSION" => &["EXPRESSION"],
        "NUMERIC_VARIABLE" => &["SIMPLE_NUMERIC_EXPRESSION", "VARIABLE"],
        "ODD_FUNCTION" => &["UNARY_BOOLEAN_EXPRESSION"],
        "OFFSET_CURVE_2D" => &["CURVE"],
        "OFFSET_CURVE_3D" => &["CURVE"],
        "OFFSET_SURFACE" => &["SURFACE"],
        "ONE_DIRECTION_REPEAT_FACTOR" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "OPEN_PATH_PROFILE" => &["SHAPE_ASPECT"],
        "OPEN_SHELL" => &["CONNECTED_FACE_SET"],
        "OR_EXPRESSION" => &["MULTIPLE_ARITY_BOOLEAN_EXPRESSION"],
        "ORDINATE_DIMENSION" => &["PROJECTION_DIRECTED_CALLOUT"],
        "ORGANIZATIONAL_ADDRESS" => &["ADDRESS"],
        "ORIENTED_CLOSED_SHELL" => &["CLOSED_SHELL"],
        "ORIENTED_EDGE" => &["EDGE"],
        "ORIENTED_FACE" => &["FACE"],
        "ORIENTED_OPEN_SHELL" => &["OPEN_SHELL"],
        "ORIENTED_PATH" => &["PATH"],
        "ORIENTED_SURFACE" => &["SURFACE"],
        "OUTER_BOUNDARY_CURVE" => &["BOUNDARY_CURVE"],
        "OVER_RIDING_STYLED_ITEM" => &["STYLED_ITEM"],
        "PACKAGE_PRODUCT_CONCEPT_FEATURE" => &["PRODUCT_CONCEPT_FEATURE"],
        "PARABOLA" => &["CONIC"],
        "PARALLEL_OFFSET" => &["DERIVED_SHAPE_ASPECT"],
        "PARALLELISM_TOLERANCE" => &["GEOMETRIC_TOLERANCE_WITH_DATUM_REFERENCE"],
        "PARAMETRIC_REPRESENTATION_CONTEXT" => &["REPRESENTATION_CONTEXT"],
        "PARTIAL_CIRCULAR_PROFILE" => &["SHAPE_ASPECT"],
        "PATH" => &["TOPOLOGICAL_REPRESENTATION_ITEM"],
        "PATH_FEATURE_COMPONENT" => &["SHAPE_ASPECT"],
        "PATH_SHAPE_REPRESENTATION" => &["SHAPE_REPRESENTATION"],
        "PATTERN_OFFSET_MEMBERSHIP" => &["FEATURE_COMPONENT_RELATIONSHIP"],
        "PATTERN_OMIT_MEMBERSHIP" => &["FEATURE_COMPONENT_RELATIONSHIP"],
        "PCURVE" => &["CURVE"],
        "PERPENDICULAR_TO" => &["DERIVED_SHAPE_ASPECT"],
        "PERPENDICULARITY_TOLERANCE" => &["GEOMETRIC_TOLERANCE_WITH_DATUM_REFERENCE"],
        "PERSON_AND_ORGANIZATION_ADDRESS" => &["ORGANIZATIONAL_ADDRESS", "PERSONAL_ADDRESS"],
        "PERSONAL_ADDRESS" => &["ADDRESS"],
        "PHYSICALLY_MODELLED_PRODUCT_DEFINITION" => {
            &["PRODUCT_DEFINITION_WITH_ASSOCIATED_DOCUMENTS"]
        }
        "PLACED_DATUM_TARGET_FEATURE" => &["DATUM_TARGET"],
        "PLACED_FEATURE" => &["SHAPE_ASPECT"],
        "PLACEMENT" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "PLANAR_BOX" => &["PLANAR_EXTENT"],
        "PLANAR_CURVE_PAIR" => &["KINEMATIC_PAIR"],
        "PLANAR_CURVE_PAIR_RANGE" => &["SIMPLE_PAIR_RANGE"],
        "PLANAR_EXTENT" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "PLANAR_PAIR" => &["KINEMATIC_PAIR"],
        "PLANAR_PAIR_RANGE" => &["SIMPLE_PAIR_RANGE"],
        "PLANAR_PAIR_VALUE" => &["PAIR_VALUE"],
        "PLANAR_SHAPE_REPRESENTATION" => &["SHAPE_REPRESENTATION"],
        "PLANE" => &["ELEMENTARY_SURFACE"],
        "PLANE_ANGLE_MEASURE_WITH_UNIT" => &["MEASURE_WITH_UNIT"],
        "PLANE_ANGLE_UNIT" => &["NAMED_UNIT"],
        "PLUS_EXPRESSION" => &["MULTIPLE_ARITY_NUMERIC_EXPRESSION"],
        "POCKET" => &["FEATURE_DEFINITION"],
        "POCKET_BOTTOM" => &["SHAPE_ASPECT"],
        "POINT" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "POINT_ON_CURVE" => &["POINT"],
        "POINT_ON_PLANAR_CURVE_PAIR" => &["KINEMATIC_PAIR"],
        "POINT_ON_PLANAR_CURVE_PAIR_RANGE" => &["SIMPLE_PAIR_RANGE"],
        "POINT_ON_PLANAR_CURVE_PAIR_VALUE" => &["PAIR_VALUE"],
        "POINT_ON_SURFACE" => &["POINT"],
        "POINT_ON_SURFACE_PAIR" => &["KINEMATIC_PAIR"],
        "POINT_ON_SURFACE_PAIR_RANGE" => &["SIMPLE_PAIR_RANGE"],
        "POINT_ON_SURFACE_PAIR_VALUE" => &["PAIR_VALUE"],
        "POINT_PLACEMENT_SHAPE_REPRESENTATION" => &["SHAPE_REPRESENTATION"],
        "POINT_REPLICA" => &["POINT"],
        "POINT_STYLE" => &["FOUNDED_ITEM"],
        "POLY_LOOP" => &["LOOP", "GEOMETRIC_REPRESENTATION_ITEM"],
        "POLYLINE" => &["BOUNDED_CURVE"],
        "POSITION_TOLERANCE" => &["GEOMETRIC_TOLERANCE"],
        "POWER_EXPRESSION" => &["BINARY_NUMERIC_EXPRESSION"],
        "PRE_DEFINED_COLOUR" => &["PRE_DEFINED_ITEM", "COLOUR"],
        "PRE_DEFINED_CURVE_FONT" => &["PRE_DEFINED_ITEM"],
        "PRE_DEFINED_DIMENSION_SYMBOL" => &["PRE_DEFINED_SYMBOL"],
        "PRE_DEFINED_GEOMETRICAL_TOLERANCE_SYMBOL" => &["PRE_DEFINED_SYMBOL"],
        "PRE_DEFINED_MARKER" => &["PRE_DEFINED_ITEM"],
        "PRE_DEFINED_POINT_MARKER_SYMBOL" => &["PRE_DEFINED_MARKER", "PRE_DEFINED_SYMBOL"],
        "PRE_DEFINED_PRESENTATION_STYLE" => &["FOUNDED_ITEM", "PRE_DEFINED_ITEM"],
        "PRE_DEFINED_SURFACE_CONDITION_SYMBOL" => &["PRE_DEFINED_SYMBOL"],
        "PRE_DEFINED_SYMBOL" => &["PRE_DEFINED_ITEM"],
        "PRE_DEFINED_TERMINATOR_SYMBOL" => &["PRE_DEFINED_SYMBOL"],
        "PRE_DEFINED_TEXT_FONT" => &["PRE_DEFINED_ITEM"],
        "PRESENTATION_AREA" => &["PRESENTATION_REPRESENTATION"],
        "PRESENTATION_REPRESENTATION" => &["REPRESENTATION"],
        "PRESENTATION_STYLE_ASSIGNMENT" => &["FOUNDED_ITEM"],
        "PRESENTATION_STYLE_BY_CONTEXT" => &["PRESENTATION_STYLE_ASSIGNMENT"],
        "PRESENTATION_VIEW" => &["PRESENTATION_REPRESENTATION"],
        "PRISMATIC_PAIR" => &["KINEMATIC_PAIR"],
        "PRISMATIC_PAIR_RANGE" => &["SIMPLE_PAIR_RANGE"],
        "PRISMATIC_PAIR_VALUE" => &["PAIR_VALUE"],
        "PROCESS_OPERATION" => &["ACTION_METHOD"],
        "PROCESS_PLAN" => &["ACTION"],
        "PRODUCT_CLASS" => &["PRODUCT_CONCEPT", "CHARACTERIZED_OBJECT"],
        "PRODUCT_CONCEPT_CONTEXT" => &["APPLICATION_CONTEXT_ELEMENT"],
        "PRODUCT_CONCEPT_FEATURE_CATEGORY" => &["GROUP"],
        "PRODUCT_CONCEPT_FEATURE_CATEGORY_USAGE" => &["GROUP_ASSIGNMENT"],
        "PRODUCT_CONTEXT" => &["APPLICATION_CONTEXT_ELEMENT"],
        "PRODUCT_DEFINITION_CONTEXT" => &["APPLICATION_CONTEXT_ELEMENT"],
        "PRODUCT_DEFINITION_EFFECTIVITY" => &["EFFECTIVITY"],
        "PRODUCT_DEFINITION_FORMATION_WITH_SPECIFIED_SOURCE" => &["PRODUCT_DEFINITION_FORMATION"],
        "PRODUCT_DEFINITION_PROCESS" => &["ACTION"],
        "PRODUCT_DEFINITION_RESOURCE" => &["ACTION_RESOURCE", "PRODUCT_DEFINITION"],
        "PRODUCT_DEFINITION_SHAPE" => &["PROPERTY_DEFINITION"],
        "PRODUCT_DEFINITION_USAGE" => &["PRODUCT_DEFINITION_RELATIONSHIP"],
        "PRODUCT_DEFINITION_WITH_ASSOCIATED_DOCUMENTS" => &["PRODUCT_DEFINITION"],
        "PRODUCT_IDENTIFICATION" => &["CONFIGURATION_ITEM", "CHARACTERIZED_OBJECT"],
        "PRODUCT_PROCESS_PLAN" => &["PRODUCT_DEFINITION_PROCESS"],
        "PRODUCT_RELATED_PRODUCT_CATEGORY" => &["PRODUCT_CATEGORY"],
        "PRODUCT_SPECIFICATION" => &["PRODUCT_IDENTIFICATION", "CONFIGURABLE_ITEM"],
        "PROJECTED_ZONE_DEFINITION" => &["TOLERANCE_ZONE_DEFINITION"],
        "PROJECTION_CURVE" => &["ANNOTATION_CURVE_OCCURRENCE"],
        "PROJECTION_DIRECTED_CALLOUT" => &["DRAUGHTING_CALLOUT"],
        "PROMISSORY_USAGE_OCCURRENCE" => &["ASSEMBLY_COMPONENT_USAGE"],
        "PROPERTY_PROCESS" => &["ACTION"],
        "QUALIFIED_REPRESENTATION_ITEM" => &["REPRESENTATION_ITEM"],
        "QUALITATIVE_UNCERTAINTY" => &["UNCERTAINTY_QUALIFIER"],
        "QUANTIFIED_ASSEMBLY_COMPONENT_USAGE" => &["ASSEMBLY_COMPONENT_USAGE"],
        "QUASI_UNIFORM_CURVE" => &["B_SPLINE_CURVE"],
        "QUASI_UNIFORM_SURFACE" => &["B_SPLINE_SURFACE"],
        "RACK_AND_PINION_PAIR" => &["KINEMATIC_PAIR"],
        "RACK_AND_PINION_PAIR_RANGE" => &["SIMPLE_PAIR_RANGE"],
        "RACK_AND_PINION_PAIR_VALUE" => &["PAIR_VALUE"],
        "RADIUS_DIMENSION" => &["DIMENSION_CURVE_DIRECTED_CALLOUT"],
        "RATIO_MEASURE_WITH_UNIT" => &["MEASURE_WITH_UNIT"],
        "RATIO_UNIT" => &["NAMED_UNIT"],
        "RATIONAL_B_SPLINE_CURVE" => &["B_SPLINE_CURVE"],
        "RATIONAL_B_SPLINE_SURFACE" => &["B_SPLINE_SURFACE"],
        "REAL_DEFINED_FUNCTION" => &["NUMERIC_DEFINED_FUNCTION"],
        "REAL_LITERAL" => &["LITERAL_NUMBER"],
        "REAL_NUMERIC_VARIABLE" => &["NUMERIC_VARIABLE"],
        "RECTANGULAR_CLOSED_PROFILE" => &["SHAPE_ASPECT"],
        "RECTANGULAR_COMPOSITE_SURFACE" => &["BOUNDED_SURFACE"],
        "RECTANGULAR_PATTERN" => &["REPLICATE_FEATURE"],
        "RECTANGULAR_TRIMMED_SURFACE" => &["BOUNDED_SURFACE"],
        "REFERENCED_MODIFIED_DATUM" => &["DATUM_REFERENCE"],
        "RELATIVE_EVENT_OCCURRENCE" => &["EVENT_OCCURRENCE"],
        "REP_ITEM_GROUP" => &["GROUP", "REPRESENTATION_ITEM"],
        "REPARAMETRISED_COMPOSITE_CURVE_SEGMENT" => &["COMPOSITE_CURVE_SEGMENT"],
        "REPLICATE_FEATURE" => &["FEATURE_DEFINITION"],
        "REPRESENTATION_RELATIONSHIP_WITH_TRANSFORMATION" => &["REPRESENTATION_RELATIONSHIP"],
        "REQUIREMENT_FOR_ACTION_RESOURCE" => &["ACTION_RESOURCE_REQUIREMENT"],
        "RESULTING_PATH" => &["MOTION_LINK_RELATIONSHIP"],
        "RETENTION" => &["ACTION"],
        "REVOLUTE_PAIR" => &["KINEMATIC_PAIR"],
        "REVOLUTE_PAIR_RANGE" => &["SIMPLE_PAIR_RANGE"],
        "REVOLUTE_PAIR_VALUE" => &["PAIR_VALUE"],
        "REVOLVED_AREA_SOLID" => &["SWEPT_AREA_SOLID"],
        "REVOLVED_FACE_SOLID" => &["SWEPT_FACE_SOLID"],
        "RIB" => &["FEATURE_DEFINITION"],
        "RIGHT_ANGULAR_WEDGE" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "RIGHT_CIRCULAR_CONE" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "RIGHT_CIRCULAR_CYLINDER" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "ROLLING_CURVE_PAIR" => &["PLANAR_CURVE_PAIR"],
        "ROLLING_CURVE_PAIR_VALUE" => &["PAIR_VALUE"],
        "ROLLING_SURFACE_PAIR" => &["SURFACE_PAIR"],
        "ROLLING_SURFACE_PAIR_VALUE" => &["PAIR_VALUE"],
        "ROUND_HOLE" => &["FEATURE_DEFINITION"],
        "ROUNDED_U_PROFILE" => &["SHAPE_ASPECT"],
        "ROUNDNESS_TOLERANCE" => &["GEOMETRIC_TOLERANCE"],
        "RULED_SURFACE_SWEPT_AREA_SOLID" => &["SURFACE_CURVE_SWEPT_AREA_SOLID"],
        "RUNOUT_ZONE_DEFINITION" => &["TOLERANCE_ZONE_DEFINITION"],
        "RUNOUT_ZONE_ORIENTATION_REFERENCE_DIRECTION" => &["RUNOUT_ZONE_ORIENTATION"],
        "SCREW_PAIR" => &["KINEMATIC_PAIR"],
        "SCREW_PAIR_RANGE" => &["SIMPLE_PAIR_RANGE"],
        "SCREW_PAIR_VALUE" => &["PAIR_VALUE"],
        "SEAM_CURVE" => &["SURFACE_CURVE"],
        "SEAM_EDGE" => &["ORIENTED_EDGE"],
        "SERIAL_NUMBERED_EFFECTIVITY" => &["EFFECTIVITY"],
        "SHAPE_ASPECT_ASSOCIATIVITY" => &["SHAPE_ASPECT_RELATIONSHIP"],
        "SHAPE_ASPECT_DERIVING_RELATIONSHIP" => &["SHAPE_ASPECT_RELATIONSHIP"],
        "SHAPE_ASPECT_TRANSITION" => &["SHAPE_ASPECT_RELATIONSHIP"],
        "SHAPE_DEFINING_RELATIONSHIP" => &["SHAPE_ASPECT_RELATIONSHIP"],
        "SHAPE_DEFINITION_REPRESENTATION" => &["PROPERTY_DEFINITION_REPRESENTATION"],
        "SHAPE_DIMENSION_REPRESENTATION" => &["SHAPE_REPRESENTATION"],
        "SHAPE_REPRESENTATION" => &["REPRESENTATION"],
        "SHAPE_REPRESENTATION_RELATIONSHIP" => &["REPRESENTATION_RELATIONSHIP"],
        "SHAPE_REPRESENTATION_WITH_PARAMETERS" => &["SHAPE_REPRESENTATION"],
        "SHELL_BASED_SURFACE_MODEL" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "SI_UNIT" => &["NAMED_UNIT"],
        "SIMPLE_BOOLEAN_EXPRESSION" => &["BOOLEAN_EXPRESSION", "SIMPLE_GENERIC_EXPRESSION"],
        "SIMPLE_GENERIC_EXPRESSION" => &["GENERIC_EXPRESSION"],
        "SIMPLE_NUMERIC_EXPRESSION" => &["NUMERIC_EXPRESSION", "SIMPLE_GENERIC_EXPRESSION"],
        "SIMPLE_STRING_EXPRESSION" => &["STRING_EXPRESSION", "SIMPLE_GENERIC_EXPRESSION"],
        "SIN_FUNCTION" => &["UNARY_FUNCTION_CALL"],
        "SLASH_EXPRESSION" => &["BINARY_NUMERIC_EXPRESSION"],
        "SLIDING_CURVE_PAIR" => &["PLANAR_CURVE_PAIR"],
        "SLIDING_CURVE_PAIR_VALUE" => &["PAIR_VALUE"],
        "SLIDING_SURFACE_PAIR" => &["SURFACE_PAIR"],
        "SLIDING_SURFACE_PAIR_VALUE" => &["PAIR_VALUE"],
        "SLOT" => &["FEATURE_DEFINITION"],
        "SLOT_END" => &["SHAPE_ASPECT"],
        "SOLID_ANGLE_MEASURE_WITH_UNIT" => &["MEASURE_WITH_UNIT"],
        "SOLID_ANGLE_UNIT" => &["NAMED_UNIT"],
        "SOLID_MODEL" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "SOLID_REPLICA" => &["SOLID_MODEL"],
        "SPECIFIED_HIGHER_USAGE_OCCURRENCE" => &["ASSEMBLY_COMPONENT_USAGE"],
        "SPHERE" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "SPHERICAL_PAIR" => &["KINEMATIC_PAIR"],
        "SPHERICAL_PAIR_RANGE" => &["SIMPLE_PAIR_RANGE"],
        "SPHERICAL_PAIR_VALUE" => &["PAIR_VALUE"],
        "SPHERICAL_SURFACE" => &["ELEMENTARY_SURFACE"],
        "SQL_MAPPABLE_DEFINED_FUNCTION" => &["DEFINED_FUNCTION"],
        "SQUARE_ROOT_FUNCTION" => &["UNARY_FUNCTION_CALL"],
        "SQUARE_U_PROFILE" => &["SHAPE_ASPECT"],
        "STANDARD_UNCERTAINTY" => &["UNCERTAINTY_QUALIFIER"],
        "STRAIGHTNESS_TOLERANCE" => &["GEOMETRIC_TOLERANCE"],
        "STRING_DEFINED_FUNCTION" => &["DEFINED_FUNCTION", "STRING_EXPRESSION"],
        "STRING_EXPRESSION" => &["EXPRESSION"],
        "STRING_LITERAL" => &["SIMPLE_STRING_EXPRESSION", "GENERIC_LITERAL"],
        "STRING_VARIABLE" => &["SIMPLE_STRING_EXPRESSION", "VARIABLE"],
        "STRUCTURED_DIMENSION_CALLOUT" => &["DRAUGHTING_CALLOUT"],
        "STYLED_ITEM" => &["REPRESENTATION_ITEM"],
        "SUBEDGE" => &["EDGE"],
        "SUBFACE" => &["FACE"],
        "SUBSTRING_EXPRESSION" => &["STRING_EXPRESSION", "MULTIPLE_ARITY_GENERIC_EXPRESSION"],
        "SURFACE" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "SURFACE_CONDITION_CALLOUT" => &["DRAUGHTING_CALLOUT"],
        "SURFACE_CURVE" => &["CURVE"],
        "SURFACE_CURVE_SWEPT_AREA_SOLID" => &["SWEPT_AREA_SOLID"],
        "SURFACE_OF_LINEAR_EXTRUSION" => &["SWEPT_SURFACE"],
        "SURFACE_OF_REVOLUTION" => &["SWEPT_SURFACE"],
        "SURFACE_PAIR" => &["KINEMATIC_PAIR"],
        "SURFACE_PAIR_RANGE" => &["SIMPLE_PAIR_RANGE"],
        "SURFACE_PATCH" => &["FOUNDED_ITEM"],
        "SURFACE_PROFILE_TOLERANCE" => &["GEOMETRIC_TOLERANCE"],
        "SURFACE_REPLICA" => &["SURFACE"],
        "SURFACE_SIDE_STYLE" => &["FOUNDED_ITEM"],
        "SURFACE_STYLE_BOUNDARY" => &["FOUNDED_ITEM"],
        "SURFACE_STYLE_CONTROL_GRID" => &["FOUNDED_ITEM"],
        "SURFACE_STYLE_FILL_AREA" => &["FOUNDED_ITEM"],
        "SURFACE_STYLE_PARAMETER_LINE" => &["FOUNDED_ITEM"],
        "SURFACE_STYLE_REFLECTANCE_AMBIENT_DIFFUSE" => &["SURFACE_STYLE_REFLECTANCE_AMBIENT"],
        "SURFACE_STYLE_REFLECTANCE_AMBIENT_DIFFUSE_SPECULAR" => {
            &["SURFACE_STYLE_REFLECTANCE_AMBIENT_DIFFUSE"]
        }
        "SURFACE_STYLE_RENDERING_WITH_PROPERTIES" => &["SURFACE_STYLE_RENDERING"],
        "SURFACE_STYLE_SEGMENTATION_CURVE" => &["FOUNDED_ITEM"],
        "SURFACE_STYLE_SILHOUETTE" => &["FOUNDED_ITEM"],
        "SURFACE_STYLE_USAGE" => &["FOUNDED_ITEM"],
        "SURFACE_TEXTURE_REPRESENTATION" => &["REPRESENTATION"],
        "SWEPT_AREA_SOLID" => &["SOLID_MODEL"],
        "SWEPT_DISK_SOLID" => &["SOLID_MODEL"],
        "SWEPT_FACE_SOLID" => &["SOLID_MODEL"],
        "SWEPT_SURFACE" => &["SURFACE"],
        "SYMBOL_REPRESENTATION" => &["REPRESENTATION"],
        "SYMBOL_REPRESENTATION_MAP" => &["REPRESENTATION_MAP"],
        "SYMBOL_STYLE" => &["FOUNDED_ITEM"],
        "SYMBOL_TARGET" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "SYMMETRIC_SHAPE_ASPECT" => &["SHAPE_ASPECT"],
        "SYMMETRY_TOLERANCE" => &["GEOMETRIC_TOLERANCE_WITH_DATUM_REFERENCE"],
        "TACTILE_APPEARANCE_REPRESENTATION" => &["REPRESENTATION"],
        "TAN_FUNCTION" => &["UNARY_FUNCTION_CALL"],
        "TANGENT" => &["DERIVED_SHAPE_ASPECT"],
        "TAPER" => &["SHAPE_ASPECT"],
        "TEE_PROFILE" => &["SHAPE_ASPECT"],
        "TERMINATOR_SYMBOL" => &["ANNOTATION_SYMBOL_OCCURRENCE"],
        "TEXT_LITERAL" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "TEXT_LITERAL_WITH_ASSOCIATED_CURVES" => &["TEXT_LITERAL"],
        "TEXT_LITERAL_WITH_BLANKING_BOX" => &["TEXT_LITERAL"],
        "TEXT_LITERAL_WITH_DELINEATION" => &["TEXT_LITERAL"],
        "TEXT_LITERAL_WITH_EXTENT" => &["TEXT_LITERAL"],
        "TEXT_STRING_REPRESENTATION" => &["REPRESENTATION"],
        "TEXT_STYLE" => &["FOUNDED_ITEM"],
        "TEXT_STYLE_WITH_BOX_CHARACTERISTICS" => &["TEXT_STYLE"],
        "TEXT_STYLE_WITH_MIRROR" => &["TEXT_STYLE"],
        "TEXT_STYLE_WITH_SPACING" => &["TEXT_STYLE"],
        "THERMODYNAMIC_TEMPERATURE_MEASURE_WITH_UNIT" => &["MEASURE_WITH_UNIT"],
        "THERMODYNAMIC_TEMPERATURE_UNIT" => &["NAMED_UNIT"],
        "THREAD" => &["FEATURE_DEFINITION"],
        "TIME_INTERVAL_BASED_EFFECTIVITY" => &["EFFECTIVITY"],
        "TIME_INTERVAL_WITH_BOUNDS" => &["TIME_INTERVAL"],
        "TIME_MEASURE_WITH_UNIT" => &["MEASURE_WITH_UNIT"],
        "TIME_UNIT" => &["NAMED_UNIT"],
        "TOLERANCE_ZONE" => &["SHAPE_ASPECT"],
        "TOPOLOGICAL_REPRESENTATION_ITEM" => &["REPRESENTATION_ITEM"],
        "TOROIDAL_SURFACE" => &["ELEMENTARY_SURFACE"],
        "TORUS" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "TOTAL_RUNOUT_TOLERANCE" => &["GEOMETRIC_TOLERANCE_WITH_DATUM_REFERENCE"],
        "TRANSITION_FEATURE" => &["SHAPE_ASPECT"],
        "TRIMMED_CURVE" => &["BOUNDED_CURVE"],
        "TWO_DIRECTION_REPEAT_FACTOR" => &["ONE_DIRECTION_REPEAT_FACTOR"],
        "UNARY_BOOLEAN_EXPRESSION" => &["BOOLEAN_EXPRESSION", "UNARY_GENERIC_EXPRESSION"],
        "UNARY_FUNCTION_CALL" => &["UNARY_NUMERIC_EXPRESSION"],
        "UNARY_GENERIC_EXPRESSION" => &["GENERIC_EXPRESSION"],
        "UNARY_NUMERIC_EXPRESSION" => &["NUMERIC_EXPRESSION", "UNARY_GENERIC_EXPRESSION"],
        "UNCERTAINTY_ASSIGNED_REPRESENTATION" => &["REPRESENTATION"],
        "UNCERTAINTY_MEASURE_WITH_UNIT" => &["MEASURE_WITH_UNIT"],
        "UNCONSTRAINED_PAIR" => &["KINEMATIC_PAIR"],
        "UNCONSTRAINED_PAIR_VALUE" => &["PAIR_VALUE"],
        "UNIFORM_CURVE" => &["B_SPLINE_CURVE"],
        "UNIFORM_SURFACE" => &["B_SPLINE_SURFACE"],
        "UNIVERSAL_PAIR" => &["KINEMATIC_PAIR"],
        "UNIVERSAL_PAIR_RANGE" => &["SIMPLE_PAIR_RANGE"],
        "UNIVERSAL_PAIR_VALUE" => &["PAIR_VALUE"],
        "VALUE_FUNCTION" => &["NUMERIC_EXPRESSION", "UNARY_GENERIC_EXPRESSION"],
        "VALUE_RANGE" => &["COMPOUND_REPRESENTATION_ITEM"],
        "VALUE_REPRESENTATION_ITEM" => &["REPRESENTATION_ITEM"],
        "VARIABLE" => &["GENERIC_VARIABLE"],
        "VECTOR" => &["GEOMETRIC_REPRESENTATION_ITEM"],
        "VECTOR_STYLE" => &["PRE_DEFINED_TERMINATOR_SYMBOL", "CURVE_STYLE"],
        "VEE_PROFILE" => &["SHAPE_ASPECT"],
        "VERTEX" => &["TOPOLOGICAL_REPRESENTATION_ITEM"],
        "VERTEX_LOOP" => &["LOOP"],
        "VERTEX_POINT" => &["VERTEX", "GEOMETRIC_REPRESENTATION_ITEM"],
        "VIEW_VOLUME" => &["FOUNDED_ITEM"],
        "VISUAL_APPEARANCE_REPRESENTATION" => &["REPRESENTATION"],
        "VOLUME_MEASURE_WITH_UNIT" => &["MEASURE_WITH_UNIT"],
        "VOLUME_UNIT" => &["DERIVED_UNIT"],
        "XOR_EXPRESSION" => &["BINARY_BOOLEAN_EXPRESSION"],
        _ => &[],
    }
}
