[build-system]
# make sure we build on the same numpy version range
# as our install numpy version range
requires = ["maturin[patchelf]>=1.12",
            "numpy>=2.0"]
build-backend = "maturin"

[project]
name = "rmesh"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
dependencies = ["numpy>=2.0"]

[project.optional-dependencies]
test = ["pytest", "trimesh"]

[tool.maturin]
manifest-path = "crates/rmesh_python/Cargo.toml"
features = ["pyo3/extension-module", "pyo3/abi3-py310"]
python-source = "python"
editable-profile = "dev"

[dependency-groups]
dev = [
    "trimesh[easy,recommend]",
    "pytest>=9.0.2",
    "ruff>=0.14.13",
    "matplotlib>=3.10.8",
    "cascadio>=0.0.18rc5",
]


[tool.pytest.ini_options]
addopts = "-p rmesh.compatibility.conftest --rmesh-compat=compare"
testpaths = ["test/trimesh/tests"]

[tool.ruff]
target-version = "py314"
line-length = 90

[tool.ruff.lint]
select = [
    "B", # bugbear
    "C", # comprehensions
    "E", # style errors
    "F", # flakes
    "I", # import sorting
    "RUF", # ruff specific rules
    "UP", # upgrade
    "W", # style warnings
    "YTT", # sys.version
    "ISC001",
    "ISC002",
    "NPY201",
    "TID251"
]
