-- Single loom.lua for all rmesh shaders.
--
-- Render shaders (shader_src/render/) go through the full shaderloom
-- pipeline: #include resolution, struct extraction, WGSL validation.
--
-- Everything else is auto-discovered by subdirectory and copied with
-- a header: shader_src/{group}/*.wgsl -> src/{group}/shaders/*.wgsl

use "config.declarative"

local function join(args)
  return table.concat(args, "/")
end

BASE = ABSSCRIPTDIR
SRC = join{BASE, "../src"}

local HEADER_TEXT = [[
!!! AUTOGENERATED BY SHADERLOOM: DO NOT EDIT HERE !!!
!!! FILE SHOULD BE EDITED IN SHADER_SRC !!!
Edit the shader source in `rmesh/shader_src` and these
built files will be automatically regenerated by `cargo build`]]

local function header(comment_prefix)
    return comment_prefix .. " " .. HEADER_TEXT:gsub("\n", "\n" .. comment_prefix .. " ") .. "\n\n"
end

-- ===== Render shaders: struct extraction + includes =====

local RENDER_OUT = join{SRC, "render/shaders"}

local STRUCT_FILE_TEMPLATE = [[
#![allow(dead_code, clippy::too_many_arguments)]
]] .. header("///") .. [[

use bytemuck::{Pod, Zeroable};

${STRUCTS}
]]

target "rust.wgpu" {
    validate = true,
    struct_definitions = {
        output = join{RENDER_OUT, "mod.rs"},
        file_template = STRUCT_FILE_TEMPLATE,
        struct_decorator = function(struct)
            struct.derive = "#[derive(Copy, Clone, Pod, Zeroable)]"
        end,
    },

    loose_files = {
        output = join{RENDER_OUT, "${NAME}"},
        file_template = header("//") .. [[${SOURCE}]],
    },
}

include_dirs(join{BASE, "render/include"})
add_shaders(join{BASE, "render/*.wgsl"})

-- ===== Compute shaders: auto-discover and copy =====
-- Every subdirectory except `render` (and `include`-like dirs) is a
-- compute shader group. Pattern: shader_src/X/*.wgsl -> src/X/shaders/*.wgsl

-- ===== Copy compute shaders before build =====
-- Run at top level (not deferred) so files exist before include_str!

local comment_header = header("//")
local find_cmd = 'find "' .. BASE .. '" -mindepth 2 -maxdepth 2 -name "*.wgsl" -not -path "*/render/*"'
local p = io.popen(find_cmd)
if p then
    for src_path in p:lines() do
        -- shader_src/voxel/cs_foo.wgsl -> group="voxel", file="cs_foo.wgsl"
        local group, filename = src_path:match("/([^/]+)/([^/]+%.wgsl)$")
        if group and filename then
            local dst_path = join{SRC, group, "shaders", filename}
            local src = io.open(src_path, "r")
            if src then
                local content = src:read("*a")
                src:close()
                local dst = io.open(dst_path, "w")
                if dst then
                    dst:write(comment_header .. content)
                    dst:close()
                end
            end
        end
    end
    p:close()
end

-- rustfmt on rendered struct definitions
defer(function()
    os.execute("rustfmt " .. join{RENDER_OUT, "mod.rs"})
end)
