-- run from this directory with `shaderloom build`

use "config.declarative"

local function join(args)
  return table.concat(args, "/")
end

BASE = ABSSCRIPTDIR
BASE_SHADERS = join{BASE, "../src/render/shaders"}

local HEADER_TEXT = [[
!!! AUTOGENERATED BY SHADERLOOM: DO NOT EDIT HERE !!!
!!! FILE SHOULD BE EDITED IN SHADER_SRC !!!
Edit the shader source in `rmesh_viewer/shader_src` and these
built files will be automatically regenerated by `cargo build`]]

local function header(comment_prefix)
    return comment_prefix .. " " .. HEADER_TEXT:gsub("\n", "\n" .. comment_prefix .. " ") .. "\n\n"
end

local STRUCT_FILE_TEMPLATE = [[
#![allow(dead_code, clippy::too_many_arguments)]
]] .. header("///") .. [[

use bytemuck::{Pod, Zeroable};

${STRUCTS}
]]

local SHADER_TEMPLATE = header("//") .. [[${SOURCE}]]

target "rust.wgpu" {
    validate = true,
    struct_definitions = {
        output = join{BASE_SHADERS, "mod.rs"},
        file_template = STRUCT_FILE_TEMPLATE,
        struct_decorator = function(struct)
            struct.derive = "#[derive(Copy, Clone, Pod, Zeroable)]"
        end,
    },

    loose_files = {
        output = join{BASE_SHADERS, "${NAME}"},
        file_template = SHADER_TEMPLATE
    },
}

include_dirs(join{BASE, "include"})
add_shaders(join{BASE, "*.wgsl"})

-- run rustfmt on the generated rust module
defer(function()
    os.execute("rustfmt -v " .. join{BASE_SHADERS, "mod.rs"})
end)
