name: Test Coverage

on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: |
          cargo install tarpaulin
          cargo tarpaulin --out xml
          bash <(curl -s https://codecov.io/bash)
