name: Build WASM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh
          rustup update
          cargo install wasm-pack
      - name: Build WASM
        run: |
          cd crates/rmesh_wasm
          wasm-pack build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./crates/rmesh_wasm/pkg
